/*
All files except if stated otherwise in the begining of the file are under the GPLv2 license:
-----------------------------------------------------------------------------------

Copyright (c) 2010-2012 Design Art Networks Ltd.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

-----------------------------------------------------------------------------------
*/
//************************************************************************
//*
//*                    Copyright DesignArt Networks
//*                         All Rights Reserved.
//*
//*         This file is automatically generated by SoC Online
//*
//*                         
//*                      !!! DO NOT MODIFY MANUALLY !!!
//*
//************************************************************************
#ifndef _dw_ddr_ctl_if_HW_REGS_H
#define _dw_ddr_ctl_if_HW_REGS_H
#ifdef __cplusplus
extern "C" {
#endif


//****************************************
//   dw_ddr_ctl (Prototype: dw_ddr_ctl)
//****************************************

//define offsets
#define dw_ddr_ctl_if_CCR_OFFSET  (0x0)
#define dw_ddr_ctl_if_DCR_OFFSET  (0x4)
#define dw_ddr_ctl_if_PCR_OFFSET  (0x8)
#define dw_ddr_ctl_if_CSR_OFFSET  (0xc)
#define dw_ddr_ctl_if_DRR_OFFSET  (0x10)
#define dw_ddr_ctl_if_TPR0_OFFSET  (0x14)
#define dw_ddr_ctl_if_TPR1_OFFSET  (0x18)
#define dw_ddr_ctl_if_TPR2_OFFSET  (0x1c)
#define dw_ddr_ctl_if_TPR3_OFFSET  (0x20)
#define dw_ddr_ctl_if_ODTCR_OFFSET  (0x44)
#define dw_ddr_ctl_if_PPER0_OFFSET  (0x48)
#define dw_ddr_ctl_if_PPER1_OFFSET  (0x4c)
#define dw_ddr_ctl_if_PPER2_OFFSET  (0x50)
#define dw_ddr_ctl_if_PPER3_OFFSET  (0x54)
#define dw_ddr_ctl_if_TPR4_OFFSET  (0x58)
#define dw_ddr_ctl_if_ALPMR_OFFSET  (0x5c)
#define dw_ddr_ctl_if_MR_MR0_OFFSET  (0x1f0)
#define dw_ddr_ctl_if_EMR_MR1_OFFSET  (0x1f4)
#define dw_ddr_ctl_if_EMR2_MR2_OFFSET  (0x1f8)
#define dw_ddr_ctl_if_EMR3_MR3_OFFSET  (0x1fc)
#define dw_ddr_ctl_if_HPCR0_OFFSET  (0x200)
#define dw_ddr_ctl_if_HPCR1_OFFSET  (0x204)
#define dw_ddr_ctl_if_HPCR2_OFFSET  (0x208)
#define dw_ddr_ctl_if_HPCR3_OFFSET  (0x20c)
#define dw_ddr_ctl_if_HPCR4_OFFSET  (0x210)
#define dw_ddr_ctl_if_HPCR5_OFFSET  (0x214)
#define dw_ddr_ctl_if_HPCR6_OFFSET  (0x218)
#define dw_ddr_ctl_if_HPCR7_OFFSET  (0x21c)
#define dw_ddr_ctl_if_HPCR8_OFFSET  (0x220)
#define dw_ddr_ctl_if_HPCR9_OFFSET  (0x224)
#define dw_ddr_ctl_if_HPCR10_OFFSET  (0x228)
#define dw_ddr_ctl_if_HPCR11_OFFSET  (0x22c)
#define dw_ddr_ctl_if_HPCR12_OFFSET  (0x230)
#define dw_ddr_ctl_if_HPCR13_OFFSET  (0x234)
#define dw_ddr_ctl_if_HPCR14_OFFSET  (0x238)
#define dw_ddr_ctl_if_HPCR15_OFFSET  (0x23c)
#define dw_ddr_ctl_if_HPCR16_OFFSET  (0x240)
#define dw_ddr_ctl_if_HPCR17_OFFSET  (0x244)
#define dw_ddr_ctl_if_HPCR18_OFFSET  (0x248)
#define dw_ddr_ctl_if_HPCR19_OFFSET  (0x24c)
#define dw_ddr_ctl_if_HPCR20_OFFSET  (0x250)
#define dw_ddr_ctl_if_HPCR21_OFFSET  (0x254)
#define dw_ddr_ctl_if_HPCR22_OFFSET  (0x258)
#define dw_ddr_ctl_if_HPCR23_OFFSET  (0x25c)
#define dw_ddr_ctl_if_HPCR24_OFFSET  (0x260)
#define dw_ddr_ctl_if_HPCR25_OFFSET  (0x264)
#define dw_ddr_ctl_if_HPCR26_OFFSET  (0x268)
#define dw_ddr_ctl_if_HPCR27_OFFSET  (0x26c)
#define dw_ddr_ctl_if_HPCR28_OFFSET  (0x270)
#define dw_ddr_ctl_if_HPCR29_OFFSET  (0x274)
#define dw_ddr_ctl_if_HPCR30_OFFSET  (0x278)
#define dw_ddr_ctl_if_HPCR31_OFFSET  (0x27c)
#define dw_ddr_ctl_if_PQCR0_OFFSET  (0x280)
#define dw_ddr_ctl_if_PQCR1_OFFSET  (0x284)
#define dw_ddr_ctl_if_PQCR2_OFFSET  (0x288)
#define dw_ddr_ctl_if_PQCR3_OFFSET  (0x28c)
#define dw_ddr_ctl_if_PQCR4_OFFSET  (0x290)
#define dw_ddr_ctl_if_PQCR5_OFFSET  (0x294)
#define dw_ddr_ctl_if_PQCR6_OFFSET  (0x298)
#define dw_ddr_ctl_if_PQCR7_OFFSET  (0x29c)
#define dw_ddr_ctl_if_MMGCR_OFFSET  (0x2a0)
#define dw_ddr_ctl_if_PUB_RIDR_OFFSET  (0x400)
#define dw_ddr_ctl_if_PHY_PIR_OFFSET  (0x404)
#define dw_ddr_ctl_if_PHY_PGCR0_OFFSET  (0x408)
#define dw_ddr_ctl_if_PHY_PGCR1_OFFSET  (0x40c)
#define dw_ddr_ctl_if_PHY_PGSR0_OFFSET  (0x410)
#define dw_ddr_ctl_if_PHY_PGSR1_OFFSET  (0x414)
#define dw_ddr_ctl_if_PHY_PLLCR_OFFSET  (0x418)
#define dw_ddr_ctl_if_PHY_PTR0_OFFSET  (0x41c)
#define dw_ddr_ctl_if_PHY_PTR1_OFFSET  (0x420)
#define dw_ddr_ctl_if_PHY_PTR2_OFFSET  (0x424)
#define dw_ddr_ctl_if_PHY_ACMDLR_OFFSET  (0x428)
#define dw_ddr_ctl_if_PHY_ACBDLR_OFFSET  (0x42c)
#define dw_ddr_ctl_if_PHY_ACIOCR_OFFSET  (0x430)
#define dw_ddr_ctl_if_PHY_DXCCR_OFFSET  (0x434)
#define dw_ddr_ctl_if_PUB_MISC_OFFSET  (0x480)
#define dw_ddr_ctl_if_PUB_SMCTL_OFFSET  (0x484)
#define dw_ddr_ctl_if_PUB_SMSTAT_OFFSET  (0x488)
#define dw_ddr_ctl_if_PUB_MR1_OFFSET  (0x48c)
#define dw_ddr_ctl_if_PUB_TWLMRD_OFFSET  (0x490)
#define dw_ddr_ctl_if_PUB_TR_ADDR0_OFFSET  (0x494)
#define dw_ddr_ctl_if_PUB_TR_ADDR1_OFFSET  (0x498)
#define dw_ddr_ctl_if_PUB_TR_ADDR2_OFFSET  (0x49c)
#define dw_ddr_ctl_if_PUB_TR_ADDR3_OFFSET  (0x4a0)
#define dw_ddr_ctl_if_PUB_TR_RD_LCDL_OFFSET  (0x4a4)
#define dw_ddr_ctl_if_PUB_PPMCFG_OFFSET  (0x4a8)
#define dw_ddr_ctl_if_PUB_SLCR_OFFSET  (0x4ac)
#define dw_ddr_ctl_if_PUB_TR_WR_LCDL_OFFSET  (0x4b4)
#define dw_ddr_ctl_if_PUB_BSTCTL_OFFSET  (0x4c0)
#define dw_ddr_ctl_if_PUB_BSTSTAT_OFFSET  (0x4c4)
#define dw_ddr_ctl_if_PUB_BSTCNT_OFFSET  (0x4c8)
#define dw_ddr_ctl_if_PUB_BSTWRD_OFFSET  (0x4cc)
#define dw_ddr_ctl_if_PUB_BSTMSK_OFFSET  (0x4d0)
#define dw_ddr_ctl_if_PUB_BSTSEED_OFFSET  (0x4d4)
#define dw_ddr_ctl_if_PUB_BSTDWEC_OFFSET  (0x4d8)
#define dw_ddr_ctl_if_PUB_BSTAWEC_OFFSET  (0x4dc)
#define dw_ddr_ctl_if_PUB_IPVR_OFFSET  (0x4f8)
#define dw_ddr_ctl_if_PUB_IPTR_OFFSET  (0x4fc)
#define dw_ddr_ctl_if_PUB_DWLCFG_0_OFFSET  (0x508)
#define dw_ddr_ctl_if_PUB_DWLCFG_1_OFFSET  (0x50c)
#define dw_ddr_ctl_if_PUB_DWLCFG_2_OFFSET  (0x510)
#define dw_ddr_ctl_if_PUB_DWLCFG_3_OFFSET  (0x514)
#define dw_ddr_ctl_if_PUB_DRLCFG_0_OFFSET  (0x518)
#define dw_ddr_ctl_if_PUB_DRLCFG_1_OFFSET  (0x51c)
#define dw_ddr_ctl_if_PUB_DRLCFG_2_OFFSET  (0x520)
#define dw_ddr_ctl_if_PUB_DRLCFG_3_OFFSET  (0x524)
#define dw_ddr_ctl_if_PHY_ZQ0CR0_OFFSET  (0x540)
#define dw_ddr_ctl_if_PHY_ZQ0CR1_OFFSET  (0x544)
#define dw_ddr_ctl_if_PHY_ZQ0SR0_OFFSET  (0x548)
#define dw_ddr_ctl_if_PHY_ZQ0SR1_OFFSET  (0x54c)
#define dw_ddr_ctl_if_PHY_DX0GCR_OFFSET  (0x5c0)
#define dw_ddr_ctl_if_PHY_DX0GSR0_OFFSET  (0x5c4)
#define dw_ddr_ctl_if_PHY_DX0GSR1_OFFSET  (0x5c8)
#define dw_ddr_ctl_if_PHY_DX0BDLR0_OFFSET  (0x5cc)
#define dw_ddr_ctl_if_PHY_DX0BDLR1_OFFSET  (0x5d0)
#define dw_ddr_ctl_if_PHY_DX0BDLR2_OFFSET  (0x5d4)
#define dw_ddr_ctl_if_PHY_DX0BDLR3_OFFSET  (0x5d8)
#define dw_ddr_ctl_if_PHY_DX0BDLR4_OFFSET  (0x5dc)
#define dw_ddr_ctl_if_PHY_DX0LCDLR0_OFFSET  (0x5e0)
#define dw_ddr_ctl_if_PHY_DX0LCDLR1_OFFSET  (0x5e4)
#define dw_ddr_ctl_if_PHY_DX0LCDLR2_OFFSET  (0x5e8)
#define dw_ddr_ctl_if_PHY_DX0MDLR_OFFSET  (0x5ec)
#define dw_ddr_ctl_if_PHY_DX1GCR_OFFSET  (0x600)
#define dw_ddr_ctl_if_PHY_DX1GSR0_OFFSET  (0x604)
#define dw_ddr_ctl_if_PHY_DX1GSR1_OFFSET  (0x608)
#define dw_ddr_ctl_if_PHY_DX1BDLR0_OFFSET  (0x60c)
#define dw_ddr_ctl_if_PHY_DX1BDLR1_OFFSET  (0x610)
#define dw_ddr_ctl_if_PHY_DX1BDLR2_OFFSET  (0x614)
#define dw_ddr_ctl_if_PHY_DX1BDLR3_OFFSET  (0x618)
#define dw_ddr_ctl_if_PHY_DX1BDLR4_OFFSET  (0x61c)
#define dw_ddr_ctl_if_PHY_DX1LCDLR0_OFFSET  (0x620)
#define dw_ddr_ctl_if_PHY_DX1LCDLR1_OFFSET  (0x624)
#define dw_ddr_ctl_if_PHY_DX1LCDLR2_OFFSET  (0x628)
#define dw_ddr_ctl_if_PHY_DX1MDLR_OFFSET  (0x62c)
#define dw_ddr_ctl_if_PHY_DX2GCR_OFFSET  (0x640)
#define dw_ddr_ctl_if_PHY_DX2GSR0_OFFSET  (0x644)
#define dw_ddr_ctl_if_PHY_DX2GSR1_OFFSET  (0x648)
#define dw_ddr_ctl_if_PHY_DX2BDLR0_OFFSET  (0x64c)
#define dw_ddr_ctl_if_PHY_DX2BDLR1_OFFSET  (0x650)
#define dw_ddr_ctl_if_PHY_DX2BDLR2_OFFSET  (0x654)
#define dw_ddr_ctl_if_PHY_DX2BDLR3_OFFSET  (0x658)
#define dw_ddr_ctl_if_PHY_DX2BDLR4_OFFSET  (0x65c)
#define dw_ddr_ctl_if_PHY_DX2LCDLR0_OFFSET  (0x660)
#define dw_ddr_ctl_if_PHY_DX2LCDLR1_OFFSET  (0x664)
#define dw_ddr_ctl_if_PHY_DX2LCDLR2_OFFSET  (0x668)
#define dw_ddr_ctl_if_PHY_DX2MDLR_OFFSET  (0x66c)
#define dw_ddr_ctl_if_PHY_DX3GCR_OFFSET  (0x680)
#define dw_ddr_ctl_if_PHY_DX3GSR0_OFFSET  (0x684)
#define dw_ddr_ctl_if_PHY_DX3GSR1_OFFSET  (0x688)
#define dw_ddr_ctl_if_PHY_DX3BDLR0_OFFSET  (0x68c)
#define dw_ddr_ctl_if_PHY_DX3BDLR1_OFFSET  (0x690)
#define dw_ddr_ctl_if_PHY_DX3BDLR2_OFFSET  (0x694)
#define dw_ddr_ctl_if_PHY_DX3BDLR3_OFFSET  (0x698)
#define dw_ddr_ctl_if_PHY_DX3BDLR4_OFFSET  (0x69c)
#define dw_ddr_ctl_if_PHY_DX3LCDLR0_OFFSET  (0x6a0)
#define dw_ddr_ctl_if_PHY_DX3LCDLR1_OFFSET  (0x6a4)
#define dw_ddr_ctl_if_PHY_DX3LCDLR2_OFFSET  (0x6a8)
#define dw_ddr_ctl_if_PHY_DX3MDLR_OFFSET  (0x6ac)
#define dw_ddr_ctl_if_PHY_DX4GCR_OFFSET  (0x6c0)
#define dw_ddr_ctl_if_PHY_DX4GSR0_OFFSET  (0x6c4)
#define dw_ddr_ctl_if_PHY_DX4GSR1_OFFSET  (0x6c8)
#define dw_ddr_ctl_if_PHY_DX4BDLR0_OFFSET  (0x6cc)
#define dw_ddr_ctl_if_PHY_DX4BDLR1_OFFSET  (0x6d0)
#define dw_ddr_ctl_if_PHY_DX4BDLR2_OFFSET  (0x6d4)
#define dw_ddr_ctl_if_PHY_DX4BDLR3_OFFSET  (0x6d8)
#define dw_ddr_ctl_if_PHY_DX4BDLR4_OFFSET  (0x6dc)
#define dw_ddr_ctl_if_PHY_DX4LCDLR0_OFFSET  (0x6e0)
#define dw_ddr_ctl_if_PHY_DX4LCDLR1_OFFSET  (0x6e4)
#define dw_ddr_ctl_if_PHY_DX4LCDLR2_OFFSET  (0x6e8)
#define dw_ddr_ctl_if_PHY_DX4MDLR_OFFSET  (0x6ec)


typedef struct dw_ddr_ctl_CCR_s
{
#ifdef BIG_ENDIAN
	UINT32 INIT_T:1;
	UINT32 rsv2:2;
	UINT32 INIT_B:1;
	UINT32 FLUSH:1;
	UINT32 rsv1:11;
	UINT32 DQSWL2:1;
	UINT32 DQSTUNE:1;
	UINT32 RRB:1;
	UINT32 rsv0:10;
	UINT32 HOSTEN:1;
	UINT32 NOMRWR:1;
	UINT32 ECCEN:1;
#else
	UINT32 ECCEN:1;
	UINT32 NOMRWR:1;
	UINT32 HOSTEN:1;
	UINT32 rsv0:10;
	UINT32 RRB:1;
	UINT32 DQSTUNE:1;
	UINT32 DQSWL2:1;
	UINT32 rsv1:11;
	UINT32 FLUSH:1;
	UINT32 INIT_B:1;
	UINT32 rsv2:2;
	UINT32 INIT_T:1;
#endif
} dw_ddr_ctl_CCR_t;

typedef struct dw_ddr_ctl_DCR_s
{
#ifdef BIG_ENDIAN
	UINT32 EXE:1;
	UINT32 CMD:4;
	UINT32 RANK:2;
	UINT32 rsv0:7;
	UINT32 RDIMM:1;
	UINT32 DO_INIT:1;
	UINT32 AMAP:2;
	UINT32 RNKALL:1;
	UINT32 RANKS:2;
	UINT32 ECC_EN:1;
	UINT32 SIOW:3;
	UINT32 DSIZE:3;
	UINT32 DIOW:2;
	UINT32 DDRMD:2;
#else
	UINT32 DDRMD:2;
	UINT32 DIOW:2;
	UINT32 DSIZE:3;
	UINT32 SIOW:3;
	UINT32 ECC_EN:1;
	UINT32 RANKS:2;
	UINT32 RNKALL:1;
	UINT32 AMAP:2;
	UINT32 DO_INIT:1;
	UINT32 RDIMM:1;
	UINT32 rsv0:7;
	UINT32 RANK:2;
	UINT32 CMD:4;
	UINT32 EXE:1;
#endif
} dw_ddr_ctl_DCR_t;

typedef struct dw_ddr_ctl_PCR_s
{
#ifdef BIG_ENDIAN
	UINT32 DQSODT:1;
	UINT32 DQODT:1;
	UINT32 ODTOE:1;
	UINT32 rsv3:1;
	UINT32 ODTOH:2;
	UINT32 rsv2:2;
	UINT32 AUTO_DATA_PDD:2;
	UINT32 rsv1:2;
	UINT32 AUTO_CMD_PDD:2;
	UINT32 rsv0:17;
	UINT32 PHY_INIT_BYP:1;
#else
	UINT32 PHY_INIT_BYP:1;
	UINT32 rsv0:17;
	UINT32 AUTO_CMD_PDD:2;
	UINT32 rsv1:2;
	UINT32 AUTO_DATA_PDD:2;
	UINT32 rsv2:2;
	UINT32 ODTOH:2;
	UINT32 rsv3:1;
	UINT32 ODTOE:1;
	UINT32 DQODT:1;
	UINT32 DQSODT:1;
#endif
} dw_ddr_ctl_PCR_t;

typedef struct dw_ddr_ctl_CSR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv2:9;
	UINT32 ECCSEC:1;
	UINT32 rsv1:2;
	UINT32 ECCERR:1;
	UINT32 INIT:1;
	UINT32 rsv0:13;
	UINT32 VT_DRIFT_ERR:1;
	UINT32 PHY_INIT_DONE:1;
	UINT32 PHY_PLL_INIT_DONE:1;
	UINT32 PHY_ZCALDONE:1;
	UINT32 PHY_CALDONE:1;
#else
	UINT32 PHY_CALDONE:1;
	UINT32 PHY_ZCALDONE:1;
	UINT32 PHY_PLL_INIT_DONE:1;
	UINT32 PHY_INIT_DONE:1;
	UINT32 VT_DRIFT_ERR:1;
	UINT32 rsv0:13;
	UINT32 INIT:1;
	UINT32 ECCERR:1;
	UINT32 rsv1:2;
	UINT32 ECCSEC:1;
	UINT32 rsv2:9;
#endif
} dw_ddr_ctl_CSR_t;

typedef struct dw_ddr_ctl_DRR_s
{
#ifdef BIG_ENDIAN
	UINT32 RD:1;
	UINT32 rsv0:1;
	UINT32 RFBURST:4;
	UINT32 tRFPRD:17;
	UINT32 tRFC:9;
#else
	UINT32 tRFC:9;
	UINT32 tRFPRD:17;
	UINT32 RFBURST:4;
	UINT32 rsv0:1;
	UINT32 RD:1;
#endif
} dw_ddr_ctl_DRR_t;

typedef struct dw_ddr_ctl_TPR0_s
{
#ifdef BIG_ENDIAN
	UINT32 tCCD:1;
	UINT32 tRC:6;
	UINT32 tRRD:4;
	UINT32 rsv1:5;
	UINT32 tRCD:4;
	UINT32 tRP:4;
	UINT32 rsv0:2;
	UINT32 tRTP:4;
	UINT32 tMRD:2;
#else
	UINT32 tMRD:2;
	UINT32 tRTP:4;
	UINT32 rsv0:2;
	UINT32 tRP:4;
	UINT32 tRCD:4;
	UINT32 rsv1:5;
	UINT32 tRRD:4;
	UINT32 tRC:6;
	UINT32 tCCD:1;
#endif
} dw_ddr_ctl_TPR0_t;

typedef struct dw_ddr_ctl_TPR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv3:9;
	UINT32 tMOD:3;
	UINT32 rsv2:1;
	UINT32 TRNKWTW:3;
	UINT32 rsv1:2;
	UINT32 TRNKRTR:2;
	UINT32 tRTODT:1;
	UINT32 rsv0:2;
	UINT32 tFAW:6;
	UINT32 tRTW:1;
	UINT32 tAOND_tAOFD:2;
#else
	UINT32 tAOND_tAOFD:2;
	UINT32 tRTW:1;
	UINT32 tFAW:6;
	UINT32 rsv0:2;
	UINT32 tRTODT:1;
	UINT32 TRNKRTR:2;
	UINT32 rsv1:2;
	UINT32 TRNKWTW:3;
	UINT32 rsv2:1;
	UINT32 tMOD:3;
	UINT32 rsv3:9;
#endif
} dw_ddr_ctl_TPR1_t;

typedef struct dw_ddr_ctl_TPR2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:13;
	UINT32 tCKE:4;
	UINT32 tXP:5;
	UINT32 tXS:10;
#else
	UINT32 tXS:10;
	UINT32 tXP:5;
	UINT32 tCKE:4;
	UINT32 rsv0:13;
#endif
} dw_ddr_ctl_TPR2_t;

typedef struct dw_ddr_ctl_TPR3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv1:8;
	UINT32 WR:5;
	UINT32 AL:4;
	UINT32 rsv0:4;
	UINT32 CWL:4;
	UINT32 CL:4;
	UINT32 BLOTF_EN:1;
	UINT32 BL:2;
#else
	UINT32 BL:2;
	UINT32 BLOTF_EN:1;
	UINT32 CL:4;
	UINT32 CWL:4;
	UINT32 rsv0:4;
	UINT32 AL:4;
	UINT32 WR:5;
	UINT32 rsv1:8;
#endif
} dw_ddr_ctl_TPR3_t;

typedef struct dw_ddr_ctl_ODTCR_s
{
#ifdef BIG_ENDIAN
	UINT32 WRODT3:4;
	UINT32 WRODT2:4;
	UINT32 WRODT1:4;
	UINT32 WRODT0:4;
	UINT32 RDODT3:4;
	UINT32 RDODT2:4;
	UINT32 RDODT1:4;
	UINT32 RDODT0:4;
#else
	UINT32 RDODT0:4;
	UINT32 RDODT1:4;
	UINT32 RDODT2:4;
	UINT32 RDODT3:4;
	UINT32 WRODT0:4;
	UINT32 WRODT1:4;
	UINT32 WRODT2:4;
	UINT32 WRODT3:4;
#endif
} dw_ddr_ctl_ODTCR_t;

typedef struct dw_ddr_ctl_PPER0_s
{
#ifdef BIG_ENDIAN
	UINT32 ZQ_CAL_EN:1;
	UINT32 rsv0:16;
	UINT32 ZQ_CALPRD:15;
#else
	UINT32 ZQ_CALPRD:15;
	UINT32 rsv0:16;
	UINT32 ZQ_CAL_EN:1;
#endif
} dw_ddr_ctl_PPER0_t;

typedef struct dw_ddr_ctl_PPER1_s
{
#ifdef BIG_ENDIAN
	UINT32 ZQCS_CAL_EN:1;
	UINT32 rsv0:16;
	UINT32 ZQCS_CALPRD:15;
#else
	UINT32 ZQCS_CALPRD:15;
	UINT32 rsv0:16;
	UINT32 ZQCS_CAL_EN:1;
#endif
} dw_ddr_ctl_PPER1_t;

typedef struct dw_ddr_ctl_PPER2_s
{
#ifdef BIG_ENDIAN
	UINT32 VT_CAL_EN:1;
	UINT32 rsv0:16;
	UINT32 VT_CALPRD:15;
#else
	UINT32 VT_CALPRD:15;
	UINT32 rsv0:16;
	UINT32 VT_CAL_EN:1;
#endif
} dw_ddr_ctl_PPER2_t;

typedef struct dw_ddr_ctl_PPER3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:31;
	UINT32 ONFLY_VTUPD:1;
#else
	UINT32 ONFLY_VTUPD:1;
	UINT32 rsv0:31;
#endif
} dw_ddr_ctl_PPER3_t;

typedef struct dw_ddr_ctl_TPR4_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv1:18;
	UINT32 tRAS:6;
	UINT32 rsv0:4;
	UINT32 tWTR:4;
#else
	UINT32 tWTR:4;
	UINT32 rsv0:4;
	UINT32 tRAS:6;
	UINT32 rsv1:18;
#endif
} dw_ddr_ctl_TPR4_t;

typedef struct dw_ddr_ctl_ALPMR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv2:5;
	UINT32 AUTOPD:1;
	UINT32 rsv1:10;
	UINT32 LPPERIOD1:8;
	UINT32 rsv0:8;
#else
	UINT32 rsv0:8;
	UINT32 LPPERIOD1:8;
	UINT32 rsv1:10;
	UINT32 AUTOPD:1;
	UINT32 rsv2:5;
#endif
} dw_ddr_ctl_ALPMR_t;

typedef struct dw_ddr_ctl_MR_MR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:16;
	UINT32 MODE_R0:16;
#else
	UINT32 MODE_R0:16;
	UINT32 rsv0:16;
#endif
} dw_ddr_ctl_MR_MR0_t;

typedef struct dw_ddr_ctl_EMR_MR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:16;
	UINT32 MODE_R1:16;
#else
	UINT32 MODE_R1:16;
	UINT32 rsv0:16;
#endif
} dw_ddr_ctl_EMR_MR1_t;

typedef struct dw_ddr_ctl_EMR2_MR2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:16;
	UINT32 MODE_R2:16;
#else
	UINT32 MODE_R2:16;
	UINT32 rsv0:16;
#endif
} dw_ddr_ctl_EMR2_MR2_t;

typedef struct dw_ddr_ctl_EMR3_MR3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:16;
	UINT32 MODE_R3:16;
#else
	UINT32 MODE_R3:16;
	UINT32 rsv0:16;
#endif
} dw_ddr_ctl_EMR3_MR3_t;

typedef struct dw_ddr_ctl_HPCR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR0_t;

typedef struct dw_ddr_ctl_HPCR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR1_t;

typedef struct dw_ddr_ctl_HPCR2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR2_t;

typedef struct dw_ddr_ctl_HPCR3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR3_t;

typedef struct dw_ddr_ctl_HPCR4_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR4_t;

typedef struct dw_ddr_ctl_HPCR5_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR5_t;

typedef struct dw_ddr_ctl_HPCR6_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR6_t;

typedef struct dw_ddr_ctl_HPCR7_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR7_t;

typedef struct dw_ddr_ctl_HPCR8_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR8_t;

typedef struct dw_ddr_ctl_HPCR9_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR9_t;

typedef struct dw_ddr_ctl_HPCR10_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR10_t;

typedef struct dw_ddr_ctl_HPCR11_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR11_t;

typedef struct dw_ddr_ctl_HPCR12_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR12_t;

typedef struct dw_ddr_ctl_HPCR13_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR13_t;

typedef struct dw_ddr_ctl_HPCR14_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR14_t;

typedef struct dw_ddr_ctl_HPCR15_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR15_t;

typedef struct dw_ddr_ctl_HPCR16_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR16_t;

typedef struct dw_ddr_ctl_HPCR17_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR17_t;

typedef struct dw_ddr_ctl_HPCR18_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR18_t;

typedef struct dw_ddr_ctl_HPCR19_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR19_t;

typedef struct dw_ddr_ctl_HPCR20_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR20_t;

typedef struct dw_ddr_ctl_HPCR21_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR21_t;

typedef struct dw_ddr_ctl_HPCR22_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR22_t;

typedef struct dw_ddr_ctl_HPCR23_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR23_t;

typedef struct dw_ddr_ctl_HPCR24_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR24_t;

typedef struct dw_ddr_ctl_HPCR25_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR25_t;

typedef struct dw_ddr_ctl_HPCR26_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR26_t;

typedef struct dw_ddr_ctl_HPCR27_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR27_t;

typedef struct dw_ddr_ctl_HPCR28_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR28_t;

typedef struct dw_ddr_ctl_HPCR29_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR29_t;

typedef struct dw_ddr_ctl_HPCR30_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR30_t;

typedef struct dw_ddr_ctl_HPCR31_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:22;
	UINT32 HNPC:1;
	UINT32 HCBP:1;
	UINT32 HPBL:8;
#else
	UINT32 HPBL:8;
	UINT32 HCBP:1;
	UINT32 HNPC:1;
	UINT32 rsv0:22;
#endif
} dw_ddr_ctl_HPCR31_t;

typedef struct dw_ddr_ctl_PQCR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:3;
	UINT32 APQS:1;
	UINT32 INTRPT:3;
	UINT32 SWAIT:5;
	UINT32 PQBL:8;
	UINT32 LPQS:2;
	UINT32 TOUTX:2;
	UINT32 TOUT:8;
#else
	UINT32 TOUT:8;
	UINT32 TOUTX:2;
	UINT32 LPQS:2;
	UINT32 PQBL:8;
	UINT32 SWAIT:5;
	UINT32 INTRPT:3;
	UINT32 APQS:1;
	UINT32 rsv0:3;
#endif
} dw_ddr_ctl_PQCR0_t;

typedef struct dw_ddr_ctl_PQCR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:3;
	UINT32 APQS:1;
	UINT32 INTRPT:3;
	UINT32 SWAIT:5;
	UINT32 PQBL:8;
	UINT32 LPQS:2;
	UINT32 TOUTX:2;
	UINT32 TOUT:8;
#else
	UINT32 TOUT:8;
	UINT32 TOUTX:2;
	UINT32 LPQS:2;
	UINT32 PQBL:8;
	UINT32 SWAIT:5;
	UINT32 INTRPT:3;
	UINT32 APQS:1;
	UINT32 rsv0:3;
#endif
} dw_ddr_ctl_PQCR1_t;

typedef struct dw_ddr_ctl_PQCR2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:3;
	UINT32 APQS:1;
	UINT32 INTRPT:3;
	UINT32 SWAIT:5;
	UINT32 PQBL:8;
	UINT32 LPQS:2;
	UINT32 TOUTX:2;
	UINT32 TOUT:8;
#else
	UINT32 TOUT:8;
	UINT32 TOUTX:2;
	UINT32 LPQS:2;
	UINT32 PQBL:8;
	UINT32 SWAIT:5;
	UINT32 INTRPT:3;
	UINT32 APQS:1;
	UINT32 rsv0:3;
#endif
} dw_ddr_ctl_PQCR2_t;

typedef struct dw_ddr_ctl_PQCR3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:3;
	UINT32 APQS:1;
	UINT32 INTRPT:3;
	UINT32 SWAIT:5;
	UINT32 PQBL:8;
	UINT32 LPQS:2;
	UINT32 TOUTX:2;
	UINT32 TOUT:8;
#else
	UINT32 TOUT:8;
	UINT32 TOUTX:2;
	UINT32 LPQS:2;
	UINT32 PQBL:8;
	UINT32 SWAIT:5;
	UINT32 INTRPT:3;
	UINT32 APQS:1;
	UINT32 rsv0:3;
#endif
} dw_ddr_ctl_PQCR3_t;

typedef struct dw_ddr_ctl_PQCR4_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:3;
	UINT32 APQS:1;
	UINT32 INTRPT:3;
	UINT32 SWAIT:5;
	UINT32 PQBL:8;
	UINT32 LPQS:2;
	UINT32 TOUTX:2;
	UINT32 TOUT:8;
#else
	UINT32 TOUT:8;
	UINT32 TOUTX:2;
	UINT32 LPQS:2;
	UINT32 PQBL:8;
	UINT32 SWAIT:5;
	UINT32 INTRPT:3;
	UINT32 APQS:1;
	UINT32 rsv0:3;
#endif
} dw_ddr_ctl_PQCR4_t;

typedef struct dw_ddr_ctl_PQCR5_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:3;
	UINT32 APQS:1;
	UINT32 INTRPT:3;
	UINT32 SWAIT:5;
	UINT32 PQBL:8;
	UINT32 LPQS:2;
	UINT32 TOUTX:2;
	UINT32 TOUT:8;
#else
	UINT32 TOUT:8;
	UINT32 TOUTX:2;
	UINT32 LPQS:2;
	UINT32 PQBL:8;
	UINT32 SWAIT:5;
	UINT32 INTRPT:3;
	UINT32 APQS:1;
	UINT32 rsv0:3;
#endif
} dw_ddr_ctl_PQCR5_t;

typedef struct dw_ddr_ctl_PQCR6_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:3;
	UINT32 APQS:1;
	UINT32 INTRPT:3;
	UINT32 SWAIT:5;
	UINT32 PQBL:8;
	UINT32 LPQS:2;
	UINT32 TOUTX:2;
	UINT32 TOUT:8;
#else
	UINT32 TOUT:8;
	UINT32 TOUTX:2;
	UINT32 LPQS:2;
	UINT32 PQBL:8;
	UINT32 SWAIT:5;
	UINT32 INTRPT:3;
	UINT32 APQS:1;
	UINT32 rsv0:3;
#endif
} dw_ddr_ctl_PQCR6_t;

typedef struct dw_ddr_ctl_PQCR7_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:3;
	UINT32 APQS:1;
	UINT32 INTRPT:3;
	UINT32 SWAIT:5;
	UINT32 PQBL:8;
	UINT32 LPQS:2;
	UINT32 TOUTX:2;
	UINT32 TOUT:8;
#else
	UINT32 TOUT:8;
	UINT32 TOUTX:2;
	UINT32 LPQS:2;
	UINT32 PQBL:8;
	UINT32 SWAIT:5;
	UINT32 INTRPT:3;
	UINT32 APQS:1;
	UINT32 rsv0:3;
#endif
} dw_ddr_ctl_PQCR7_t;

typedef struct dw_ddr_ctl_MMGCR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:30;
	UINT32 UHPP:2;
#else
	UINT32 UHPP:2;
	UINT32 rsv0:30;
#endif
} dw_ddr_ctl_MMGCR_t;

typedef struct dw_ddr_ctl_PUB_RIDR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:16;
	UINT32 mjrev:8;
	UINT32 mnrev:8;
#else
	UINT32 mnrev:8;
	UINT32 mjrev:8;
	UINT32 rsv0:16;
#endif
} dw_ddr_ctl_PUB_RIDR_t;

typedef struct dw_ddr_ctl_PHY_PIR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv1:3;
	UINT32 inhvt:1;
	UINT32 zcalupd:1;
	UINT32 zcal:1;
	UINT32 zcalbyp:1;
	UINT32 zcksel:2;
	UINT32 dldlmt:8;
	UINT32 fdepth:2;
	UINT32 lpfdepth:2;
	UINT32 lpfen:1;
	UINT32 mdlen:1;
	UINT32 pllpd:1;
	UINT32 pllrst:1;
	UINT32 phyhrst:1;
	UINT32 phyrst:1;
	UINT32 rsv0:1;
	UINT32 calbyp:1;
	UINT32 cal:1;
	UINT32 initbyp:1;
	UINT32 phyinit:1;
#else
	UINT32 phyinit:1;
	UINT32 initbyp:1;
	UINT32 cal:1;
	UINT32 calbyp:1;
	UINT32 rsv0:1;
	UINT32 phyrst:1;
	UINT32 phyhrst:1;
	UINT32 pllrst:1;
	UINT32 pllpd:1;
	UINT32 mdlen:1;
	UINT32 lpfen:1;
	UINT32 lpfdepth:2;
	UINT32 fdepth:2;
	UINT32 dldlmt:8;
	UINT32 zcksel:2;
	UINT32 zcalbyp:1;
	UINT32 zcal:1;
	UINT32 zcalupd:1;
	UINT32 inhvt:1;
	UINT32 rsv1:3;
#endif
} dw_ddr_ctl_PHY_PIR_t;

typedef struct dw_ddr_ctl_PHY_PGCR0_s
{
#ifdef BIG_ENDIAN
	UINT32 cken:6;
	UINT32 lbmode:1;
	UINT32 lbcksel:2;
	UINT32 lbsel:2;
	UINT32 iolb:1;
	UINT32 plcksel:1;
	UINT32 dtosel:5;
	UINT32 oscwdl:2;
	UINT32 oscdiv:3;
	UINT32 oscen:1;
	UINT32 dltst:1;
	UINT32 dltmode:1;
	UINT32 rdbvt:1;
	UINT32 wdbvt:1;
	UINT32 rglvt:1;
	UINT32 rdlvt:1;
	UINT32 wdlvt:1;
	UINT32 wllvt:1;
#else
	UINT32 wllvt:1;
	UINT32 wdlvt:1;
	UINT32 rdlvt:1;
	UINT32 rglvt:1;
	UINT32 wdbvt:1;
	UINT32 rdbvt:1;
	UINT32 dltmode:1;
	UINT32 dltst:1;
	UINT32 oscen:1;
	UINT32 oscdiv:3;
	UINT32 oscwdl:2;
	UINT32 dtosel:5;
	UINT32 plcksel:1;
	UINT32 iolb:1;
	UINT32 lbsel:2;
	UINT32 lbcksel:2;
	UINT32 lbmode:1;
	UINT32 cken:6;
#endif
} dw_ddr_ctl_PHY_PGCR0_t;

typedef struct dw_ddr_ctl_PHY_PGCR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv1:16;
	UINT32 rstoe:1;
	UINT32 odtoe:1;
	UINT32 ckeoe:1;
	UINT32 ckoe:1;
	UINT32 rsv0:3;
	UINT32 ioddrm:2;
	UINT32 wlselt:1;
	UINT32 wlrank:2;
	UINT32 wluncrt:1;
	UINT32 wlstep:1;
	UINT32 wlfull:1;
	UINT32 wlen:1;
#else
	UINT32 wlen:1;
	UINT32 wlfull:1;
	UINT32 wlstep:1;
	UINT32 wluncrt:1;
	UINT32 wlrank:2;
	UINT32 wlselt:1;
	UINT32 ioddrm:2;
	UINT32 rsv0:3;
	UINT32 ckoe:1;
	UINT32 ckeoe:1;
	UINT32 odtoe:1;
	UINT32 rstoe:1;
	UINT32 rsv1:16;
#endif
} dw_ddr_ctl_PHY_PGCR1_t;

typedef struct dw_ddr_ctl_PHY_PGSR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:26;
	UINT32 aplock:1;
	UINT32 wlerr:1;
	UINT32 wl:1;
	UINT32 cal:1;
	UINT32 pllinit:1;
	UINT32 init:1;
#else
	UINT32 init:1;
	UINT32 pllinit:1;
	UINT32 cal:1;
	UINT32 wl:1;
	UINT32 wlerr:1;
	UINT32 aplock:1;
	UINT32 rsv0:26;
#endif
} dw_ddr_ctl_PHY_PGSR0_t;

typedef struct dw_ddr_ctl_PHY_PGSR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:7;
	UINT32 dltcode:24;
	UINT32 dltdone:1;
#else
	UINT32 dltdone:1;
	UINT32 dltcode:24;
	UINT32 rsv0:7;
#endif
} dw_ddr_ctl_PHY_PGSR1_t;

typedef struct dw_ddr_ctl_PHY_PLLCR_s
{
#ifdef BIG_ENDIAN
	UINT32 byp:1;
	UINT32 rsv0:11;
	UINT32 frqsel:2;
	UINT32 qpmode:1;
	UINT32 cppc:4;
	UINT32 cpic:2;
	UINT32 gshift:1;
	UINT32 atoen:4;
	UINT32 atc:4;
	UINT32 dtc:2;
#else
	UINT32 dtc:2;
	UINT32 atc:4;
	UINT32 atoen:4;
	UINT32 gshift:1;
	UINT32 cpic:2;
	UINT32 cppc:4;
	UINT32 qpmode:1;
	UINT32 frqsel:2;
	UINT32 rsv0:11;
	UINT32 byp:1;
#endif
} dw_ddr_ctl_PHY_PLLCR_t;

typedef struct dw_ddr_ctl_PHY_PTR0_s
{
#ifdef BIG_ENDIAN
	UINT32 tpllpd:11;
	UINT32 tpllgs:15;
	UINT32 tphyrst:6;
#else
	UINT32 tphyrst:6;
	UINT32 tpllgs:15;
	UINT32 tpllpd:11;
#endif
} dw_ddr_ctl_PHY_PTR0_t;

typedef struct dw_ddr_ctl_PHY_PTR1_s
{
#ifdef BIG_ENDIAN
	UINT32 tplllock:16;
	UINT32 rsv0:3;
	UINT32 tpllrst:13;
#else
	UINT32 tpllrst:13;
	UINT32 rsv0:3;
	UINT32 tplllock:16;
#endif
} dw_ddr_ctl_PHY_PTR1_t;

typedef struct dw_ddr_ctl_PHY_PTR2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:11;
	UINT32 twldlys:5;
	UINT32 twlo:4;
	UINT32 tcalh:4;
	UINT32 tcals:4;
	UINT32 tcalon:4;
#else
	UINT32 tcalon:4;
	UINT32 tcals:4;
	UINT32 tcalh:4;
	UINT32 twlo:4;
	UINT32 twldlys:5;
	UINT32 rsv0:11;
#endif
} dw_ddr_ctl_PHY_PTR2_t;

typedef struct dw_ddr_ctl_PHY_ACMDLR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 mdld:8;
	UINT32 tprd:8;
	UINT32 iprd:8;
#else
	UINT32 iprd:8;
	UINT32 tprd:8;
	UINT32 mdld:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_ACMDLR_t;

typedef struct dw_ddr_ctl_PHY_ACBDLR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 acbd:6;
	UINT32 ck2bd:6;
	UINT32 ck1bd:6;
	UINT32 ck0bd:6;
#else
	UINT32 ck0bd:6;
	UINT32 ck1bd:6;
	UINT32 ck2bd:6;
	UINT32 acbd:6;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_ACBDLR_t;

typedef struct dw_ddr_ctl_PHY_ACIOCR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:1;
	UINT32 acsr:2;
	UINT32 rstpdr:1;
	UINT32 rstpdd:1;
	UINT32 rstodt:1;
	UINT32 rankpdr:4;
	UINT32 rankpdd:4;
	UINT32 rankodt:4;
	UINT32 ckpdr:3;
	UINT32 ckpdd:3;
	UINT32 ckodt:3;
	UINT32 acpdr:1;
	UINT32 acpdd:1;
	UINT32 acodt:1;
	UINT32 acoe:1;
	UINT32 aciom:1;
#else
	UINT32 aciom:1;
	UINT32 acoe:1;
	UINT32 acodt:1;
	UINT32 acpdd:1;
	UINT32 acpdr:1;
	UINT32 ckodt:3;
	UINT32 ckpdd:3;
	UINT32 ckpdr:3;
	UINT32 rankodt:4;
	UINT32 rankpdd:4;
	UINT32 rankpdr:4;
	UINT32 rstodt:1;
	UINT32 rstpdd:1;
	UINT32 rstpdr:1;
	UINT32 acsr:2;
	UINT32 rsv0:1;
#endif
} dw_ddr_ctl_PHY_ACIOCR_t;

typedef struct dw_ddr_ctl_PHY_DXCCR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:17;
	UINT32 dxsr:2;
	UINT32 dqsnres:4;
	UINT32 dqsres:4;
	UINT32 dxpdr:1;
	UINT32 dxpdd:1;
	UINT32 mdlen:1;
	UINT32 dxiom:1;
	UINT32 dxodt:1;
#else
	UINT32 dxodt:1;
	UINT32 dxiom:1;
	UINT32 mdlen:1;
	UINT32 dxpdd:1;
	UINT32 dxpdr:1;
	UINT32 dqsres:4;
	UINT32 dqsnres:4;
	UINT32 dxsr:2;
	UINT32 rsv0:17;
#endif
} dw_ddr_ctl_PHY_DXCCR_t;

typedef struct dw_ddr_ctl_PUB_MISC_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:28;
	UINT32 pub_en_status:1;
	UINT32 wbds_dm_dis:1;
	UINT32 misc_reset:1;
	UINT32 tr_en:1;
#else
	UINT32 tr_en:1;
	UINT32 misc_reset:1;
	UINT32 wbds_dm_dis:1;
	UINT32 pub_en_status:1;
	UINT32 rsv0:28;
#endif
} dw_ddr_ctl_PUB_MISC_t;

typedef struct dw_ddr_ctl_PUB_SMCTL_s
{
#ifdef BIG_ENDIAN
	UINT32 mscmp:16;
	UINT32 mswait:16;
#else
	UINT32 mswait:16;
	UINT32 mscmp:16;
#endif
} dw_ddr_ctl_PUB_SMCTL_t;

typedef struct dw_ddr_ctl_PUB_SMSTAT_s
{
#ifdef BIG_ENDIAN
	UINT32 mse:16;
	UINT32 mss:16;
#else
	UINT32 mss:16;
	UINT32 mse:16;
#endif
} dw_ddr_ctl_PUB_SMSTAT_t;

typedef struct dw_ddr_ctl_PUB_MR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:16;
	UINT32 mr1:16;
#else
	UINT32 mr1:16;
	UINT32 rsv0:16;
#endif
} dw_ddr_ctl_PUB_MR1_t;

typedef struct dw_ddr_ctl_PUB_TWLMRD_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:26;
	UINT32 twlmrd:6;
#else
	UINT32 twlmrd:6;
	UINT32 rsv0:26;
#endif
} dw_ddr_ctl_PUB_TWLMRD_t;

typedef struct dw_ddr_ctl_PUB_TR_ADDR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 row:17;
	UINT32 ba:3;
	UINT32 col:10;
#else
	UINT32 col:10;
	UINT32 ba:3;
	UINT32 row:17;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PUB_TR_ADDR0_t;

typedef struct dw_ddr_ctl_PUB_TR_ADDR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 row:17;
	UINT32 ba:3;
	UINT32 col:10;
#else
	UINT32 col:10;
	UINT32 ba:3;
	UINT32 row:17;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PUB_TR_ADDR1_t;

typedef struct dw_ddr_ctl_PUB_TR_ADDR2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 row:17;
	UINT32 ba:3;
	UINT32 col:10;
#else
	UINT32 col:10;
	UINT32 ba:3;
	UINT32 row:17;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PUB_TR_ADDR2_t;

typedef struct dw_ddr_ctl_PUB_TR_ADDR3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 row:17;
	UINT32 ba:3;
	UINT32 col:10;
#else
	UINT32 col:10;
	UINT32 ba:3;
	UINT32 row:17;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PUB_TR_ADDR3_t;

typedef struct dw_ddr_ctl_PUB_TR_RD_LCDL_s
{
#ifdef BIG_ENDIAN
	UINT32 lcdl_max:8;
	UINT32 lcdl_min:8;
	UINT32 rsv0:8;
	UINT32 lcdl_shift:8;
#else
	UINT32 lcdl_shift:8;
	UINT32 rsv0:8;
	UINT32 lcdl_min:8;
	UINT32 lcdl_max:8;
#endif
} dw_ddr_ctl_PUB_TR_RD_LCDL_t;

typedef struct dw_ddr_ctl_PUB_PPMCFG_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:19;
	UINT32 pprank_dis:4;
	UINT32 rpmem_dis:8;
	UINT32 ppmem_en:1;
#else
	UINT32 ppmem_en:1;
	UINT32 rpmem_dis:8;
	UINT32 pprank_dis:4;
	UINT32 rsv0:19;
#endif
} dw_ddr_ctl_PUB_PPMCFG_t;

typedef struct dw_ddr_ctl_PUB_SLCR_s
{
#ifdef BIG_ENDIAN
	UINT32 wl_lat:4;
	UINT32 gdqs_lat:4;
	UINT32 dv_lat:4;
	UINT32 rsv2:2;
	UINT32 dv_len:2;
	UINT32 ds_lat:4;
	UINT32 rsv1:2;
	UINT32 ds_len:2;
	UINT32 qs_lat:4;
	UINT32 rsv0:2;
	UINT32 qs_len:2;
#else
	UINT32 qs_len:2;
	UINT32 rsv0:2;
	UINT32 qs_lat:4;
	UINT32 ds_len:2;
	UINT32 rsv1:2;
	UINT32 ds_lat:4;
	UINT32 dv_len:2;
	UINT32 rsv2:2;
	UINT32 dv_lat:4;
	UINT32 gdqs_lat:4;
	UINT32 wl_lat:4;
#endif
} dw_ddr_ctl_PUB_SLCR_t;

typedef struct dw_ddr_ctl_PUB_TR_WR_LCDL_s
{
#ifdef BIG_ENDIAN
	UINT32 lcdl_max:8;
	UINT32 lcdl_min:8;
	UINT32 rsv0:8;
	UINT32 lcdl_shift:8;
#else
	UINT32 lcdl_shift:8;
	UINT32 rsv0:8;
	UINT32 lcdl_min:8;
	UINT32 lcdl_max:8;
#endif
} dw_ddr_ctl_PUB_TR_WR_LCDL_t;

typedef struct dw_ddr_ctl_PUB_BSTCTL_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:18;
	UINT32 x8_sel:4;
	UINT32 brun:1;
	UINT32 ce:1;
	UINT32 walk:1;
	UINT32 dm_en:1;
	UINT32 a_en:1;
	UINT32 wla:1;
	UINT32 wlb:1;
	UINT32 wldm:1;
	UINT32 man:1;
	UINT32 en:1;
#else
	UINT32 en:1;
	UINT32 man:1;
	UINT32 wldm:1;
	UINT32 wlb:1;
	UINT32 wla:1;
	UINT32 a_en:1;
	UINT32 dm_en:1;
	UINT32 walk:1;
	UINT32 ce:1;
	UINT32 brun:1;
	UINT32 x8_sel:4;
	UINT32 rsv0:18;
#endif
} dw_ddr_ctl_PUB_BSTCTL_t;

typedef struct dw_ddr_ctl_PUB_BSTSTAT_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv1:26;
	UINT32 DME:1;
	UINT32 DE:1;
	UINT32 AE:1;
	UINT32 rsv0:2;
	UINT32 run:1;
#else
	UINT32 run:1;
	UINT32 rsv0:2;
	UINT32 AE:1;
	UINT32 DE:1;
	UINT32 DME:1;
	UINT32 rsv1:26;
#endif
} dw_ddr_ctl_PUB_BSTSTAT_t;

typedef struct dw_ddr_ctl_PUB_BSTCNT_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:16;
	UINT32 wc:16;
#else
	UINT32 wc:16;
	UINT32 rsv0:16;
#endif
} dw_ddr_ctl_PUB_BSTCNT_t;

typedef struct dw_ddr_ctl_PUB_BSTWRD_s
{
#ifdef BIG_ENDIAN
	UINT32 wlb:16;
	UINT32 wla:16;
#else
	UINT32 wla:16;
	UINT32 wlb:16;
#endif
} dw_ddr_ctl_PUB_BSTWRD_t;

typedef struct dw_ddr_ctl_PUB_BSTMSK_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:16;
	UINT32 wlmsk:16;
#else
	UINT32 wlmsk:16;
	UINT32 rsv0:16;
#endif
} dw_ddr_ctl_PUB_BSTMSK_t;

typedef struct dw_ddr_ctl_PUB_BSTSEED_s
{
#ifdef BIG_ENDIAN
	UINT32 seed:32;
#else
	UINT32 seed:32;
#endif
} dw_ddr_ctl_PUB_BSTSEED_t;

typedef struct dw_ddr_ctl_PUB_BSTDWEC_s
{
#ifdef BIG_ENDIAN
	UINT32 dm_wec:16;
	UINT32 d_wec:16;
#else
	UINT32 d_wec:16;
	UINT32 dm_wec:16;
#endif
} dw_ddr_ctl_PUB_BSTDWEC_t;

typedef struct dw_ddr_ctl_PUB_BSTAWEC_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:16;
	UINT32 a_wec:16;
#else
	UINT32 a_wec:16;
	UINT32 rsv0:16;
#endif
} dw_ddr_ctl_PUB_BSTAWEC_t;

typedef struct dw_ddr_ctl_PUB_IPVR_s
{
#ifdef BIG_ENDIAN
	UINT32 pub_ipvr:32;
#else
	UINT32 pub_ipvr:32;
#endif
} dw_ddr_ctl_PUB_IPVR_t;

typedef struct dw_ddr_ctl_PUB_IPTR_s
{
#ifdef BIG_ENDIAN
	UINT32 pub_iptr:32;
#else
	UINT32 pub_iptr:32;
#endif
} dw_ddr_ctl_PUB_IPTR_t;

typedef struct dw_ddr_ctl_PUB_DWLCFG_0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:17;
	UINT32 dwl_x8_4:3;
	UINT32 dwl_x8_3:3;
	UINT32 dwl_x8_2:3;
	UINT32 dwl_x8_1:3;
	UINT32 dwl_x8_0:3;
#else
	UINT32 dwl_x8_0:3;
	UINT32 dwl_x8_1:3;
	UINT32 dwl_x8_2:3;
	UINT32 dwl_x8_3:3;
	UINT32 dwl_x8_4:3;
	UINT32 rsv0:17;
#endif
} dw_ddr_ctl_PUB_DWLCFG_0_t;

typedef struct dw_ddr_ctl_PUB_DWLCFG_1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:17;
	UINT32 dwl_x8_4:3;
	UINT32 dwl_x8_3:3;
	UINT32 dwl_x8_2:3;
	UINT32 dwl_x8_1:3;
	UINT32 dwl_x8_0:3;
#else
	UINT32 dwl_x8_0:3;
	UINT32 dwl_x8_1:3;
	UINT32 dwl_x8_2:3;
	UINT32 dwl_x8_3:3;
	UINT32 dwl_x8_4:3;
	UINT32 rsv0:17;
#endif
} dw_ddr_ctl_PUB_DWLCFG_1_t;

typedef struct dw_ddr_ctl_PUB_DWLCFG_2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:17;
	UINT32 dwl_x8_4:3;
	UINT32 dwl_x8_3:3;
	UINT32 dwl_x8_2:3;
	UINT32 dwl_x8_1:3;
	UINT32 dwl_x8_0:3;
#else
	UINT32 dwl_x8_0:3;
	UINT32 dwl_x8_1:3;
	UINT32 dwl_x8_2:3;
	UINT32 dwl_x8_3:3;
	UINT32 dwl_x8_4:3;
	UINT32 rsv0:17;
#endif
} dw_ddr_ctl_PUB_DWLCFG_2_t;

typedef struct dw_ddr_ctl_PUB_DWLCFG_3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:17;
	UINT32 dwl_x8_4:3;
	UINT32 dwl_x8_3:3;
	UINT32 dwl_x8_2:3;
	UINT32 dwl_x8_1:3;
	UINT32 dwl_x8_0:3;
#else
	UINT32 dwl_x8_0:3;
	UINT32 dwl_x8_1:3;
	UINT32 dwl_x8_2:3;
	UINT32 dwl_x8_3:3;
	UINT32 dwl_x8_4:3;
	UINT32 rsv0:17;
#endif
} dw_ddr_ctl_PUB_DWLCFG_3_t;

typedef struct dw_ddr_ctl_PUB_DRLCFG_0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:17;
	UINT32 drl_x8_4:3;
	UINT32 drl_x8_3:3;
	UINT32 drl_x8_2:3;
	UINT32 drl_x8_1:3;
	UINT32 drl_x8_0:3;
#else
	UINT32 drl_x8_0:3;
	UINT32 drl_x8_1:3;
	UINT32 drl_x8_2:3;
	UINT32 drl_x8_3:3;
	UINT32 drl_x8_4:3;
	UINT32 rsv0:17;
#endif
} dw_ddr_ctl_PUB_DRLCFG_0_t;

typedef struct dw_ddr_ctl_PUB_DRLCFG_1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:17;
	UINT32 drl_x8_4:3;
	UINT32 drl_x8_3:3;
	UINT32 drl_x8_2:3;
	UINT32 drl_x8_1:3;
	UINT32 drl_x8_0:3;
#else
	UINT32 drl_x8_0:3;
	UINT32 drl_x8_1:3;
	UINT32 drl_x8_2:3;
	UINT32 drl_x8_3:3;
	UINT32 drl_x8_4:3;
	UINT32 rsv0:17;
#endif
} dw_ddr_ctl_PUB_DRLCFG_1_t;

typedef struct dw_ddr_ctl_PUB_DRLCFG_2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:17;
	UINT32 drl_x8_4:3;
	UINT32 drl_x8_3:3;
	UINT32 drl_x8_2:3;
	UINT32 drl_x8_1:3;
	UINT32 drl_x8_0:3;
#else
	UINT32 drl_x8_0:3;
	UINT32 drl_x8_1:3;
	UINT32 drl_x8_2:3;
	UINT32 drl_x8_3:3;
	UINT32 drl_x8_4:3;
	UINT32 rsv0:17;
#endif
} dw_ddr_ctl_PUB_DRLCFG_2_t;

typedef struct dw_ddr_ctl_PUB_DRLCFG_3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:17;
	UINT32 drl_x8_4:3;
	UINT32 drl_x8_3:3;
	UINT32 drl_x8_2:3;
	UINT32 drl_x8_1:3;
	UINT32 drl_x8_0:3;
#else
	UINT32 drl_x8_0:3;
	UINT32 drl_x8_1:3;
	UINT32 drl_x8_2:3;
	UINT32 drl_x8_3:3;
	UINT32 drl_x8_4:3;
	UINT32 rsv0:17;
#endif
} dw_ddr_ctl_PUB_DRLCFG_3_t;

typedef struct dw_ddr_ctl_PHY_ZQ0CR0_s
{
#ifdef BIG_ENDIAN
	UINT32 zqpd:1;
	UINT32 zcal:1;
	UINT32 zcalbyp:1;
	UINT32 zden:1;
	UINT32 zdata:28;
#else
	UINT32 zdata:28;
	UINT32 zden:1;
	UINT32 zcalbyp:1;
	UINT32 zcal:1;
	UINT32 zqpd:1;
#endif
} dw_ddr_ctl_PHY_ZQ0CR0_t;

typedef struct dw_ddr_ctl_PHY_ZQ0CR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:24;
	UINT32 zprog:8;
#else
	UINT32 zprog:8;
	UINT32 rsv0:24;
#endif
} dw_ddr_ctl_PHY_ZQ0CR1_t;

typedef struct dw_ddr_ctl_PHY_ZQ0SR0_s
{
#ifdef BIG_ENDIAN
	UINT32 zdone:1;
	UINT32 zerr:1;
	UINT32 rsv0:2;
	UINT32 zctrl:28;
#else
	UINT32 zctrl:28;
	UINT32 rsv0:2;
	UINT32 zerr:1;
	UINT32 zdone:1;
#endif
} dw_ddr_ctl_PHY_ZQ0SR0_t;

typedef struct dw_ddr_ctl_PHY_ZQ0SR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:24;
	UINT32 opu:2;
	UINT32 opd:2;
	UINT32 zpu:2;
	UINT32 zpd:2;
#else
	UINT32 zpd:2;
	UINT32 zpu:2;
	UINT32 opd:2;
	UINT32 opu:2;
	UINT32 rsv0:24;
#endif
} dw_ddr_ctl_PHY_ZQ0SR1_t;

typedef struct dw_ddr_ctl_PHY_DX0GCR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:20;
	UINT32 dqsrpd:1;
	UINT32 dxpdr:1;
	UINT32 dxpdd:1;
	UINT32 mdlen:1;
	UINT32 wlrken:4;
	UINT32 dxiom:1;
	UINT32 dxodt:1;
	UINT32 calbyp:1;
	UINT32 dxen:1;
#else
	UINT32 dxen:1;
	UINT32 calbyp:1;
	UINT32 dxodt:1;
	UINT32 dxiom:1;
	UINT32 wlrken:4;
	UINT32 mdlen:1;
	UINT32 dxpdd:1;
	UINT32 dxpdr:1;
	UINT32 dqsrpd:1;
	UINT32 rsv0:20;
#endif
} dw_ddr_ctl_PHY_DX0GCR_t;

typedef struct dw_ddr_ctl_PHY_DX0GSR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 gdqsprd:8;
	UINT32 dplock:1;
	UINT32 wlprd:8;
	UINT32 wlerr:1;
	UINT32 wldone:1;
	UINT32 wlcal:1;
	UINT32 gdqscal:1;
	UINT32 rdqsncal:1;
	UINT32 rdqscal:1;
	UINT32 wdqcal:1;
#else
	UINT32 wdqcal:1;
	UINT32 rdqscal:1;
	UINT32 rdqsncal:1;
	UINT32 gdqscal:1;
	UINT32 wlcal:1;
	UINT32 wldone:1;
	UINT32 wlerr:1;
	UINT32 wlprd:8;
	UINT32 dplock:1;
	UINT32 gdqsprd:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX0GSR0_t;

typedef struct dw_ddr_ctl_PHY_DX0GSR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:13;
	UINT32 dltcode:18;
	UINT32 dltdone:1;
#else
	UINT32 dltdone:1;
	UINT32 dltcode:18;
	UINT32 rsv0:13;
#endif
} dw_ddr_ctl_PHY_DX0GSR1_t;

typedef struct dw_ddr_ctl_PHY_DX0BDLR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dq4wbd:6;
	UINT32 dq3wbd:6;
	UINT32 dq2wbd:6;
	UINT32 dq1wbd:6;
	UINT32 dq0wbd:6;
#else
	UINT32 dq0wbd:6;
	UINT32 dq1wbd:6;
	UINT32 dq2wbd:6;
	UINT32 dq3wbd:6;
	UINT32 dq4wbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX0BDLR0_t;

typedef struct dw_ddr_ctl_PHY_DX0BDLR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dswbd:6;
	UINT32 dmwbd:6;
	UINT32 dq7wbd:6;
	UINT32 dq6wbd:6;
	UINT32 dq5wbd:6;
#else
	UINT32 dq5wbd:6;
	UINT32 dq6wbd:6;
	UINT32 dq7wbd:6;
	UINT32 dmwbd:6;
	UINT32 dswbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX0BDLR1_t;

typedef struct dw_ddr_ctl_PHY_DX0BDLR2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 dsnrbd:6;
	UINT32 dsrbd:6;
	UINT32 dqoebd:6;
	UINT32 dsoebd:6;
#else
	UINT32 dsoebd:6;
	UINT32 dqoebd:6;
	UINT32 dsrbd:6;
	UINT32 dsnrbd:6;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX0BDLR2_t;

typedef struct dw_ddr_ctl_PHY_DX0BDLR3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dq4rbd:6;
	UINT32 dq3rbd:6;
	UINT32 dq2rbd:6;
	UINT32 dq1rbd:6;
	UINT32 dq0rbd:6;
#else
	UINT32 dq0rbd:6;
	UINT32 dq1rbd:6;
	UINT32 dq2rbd:6;
	UINT32 dq3rbd:6;
	UINT32 dq4rbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX0BDLR3_t;

typedef struct dw_ddr_ctl_PHY_DX0BDLR4_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 dmrbd:6;
	UINT32 dq7rbd:6;
	UINT32 dq6rbd:6;
	UINT32 dq5rbd:6;
#else
	UINT32 dq5rbd:6;
	UINT32 dq6rbd:6;
	UINT32 dq7rbd:6;
	UINT32 dmrbd:6;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX0BDLR4_t;

typedef struct dw_ddr_ctl_PHY_DX0LCDLR0_s
{
#ifdef BIG_ENDIAN
	UINT32 r3wld:8;
	UINT32 r2wld:8;
	UINT32 r1wld:8;
	UINT32 r0wld:8;
#else
	UINT32 r0wld:8;
	UINT32 r1wld:8;
	UINT32 r2wld:8;
	UINT32 r3wld:8;
#endif
} dw_ddr_ctl_PHY_DX0LCDLR0_t;

typedef struct dw_ddr_ctl_PHY_DX0LCDLR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 rdqsnd:8;
	UINT32 rdqsd:8;
	UINT32 wdqd:8;
#else
	UINT32 wdqd:8;
	UINT32 rdqsd:8;
	UINT32 rdqsnd:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX0LCDLR1_t;

typedef struct dw_ddr_ctl_PHY_DX0LCDLR2_s
{
#ifdef BIG_ENDIAN
	UINT32 r3dqsgd:8;
	UINT32 r2dqsgd:8;
	UINT32 r1dqsgd:8;
	UINT32 r0dqsgd:8;
#else
	UINT32 r0dqsgd:8;
	UINT32 r1dqsgd:8;
	UINT32 r2dqsgd:8;
	UINT32 r3dqsgd:8;
#endif
} dw_ddr_ctl_PHY_DX0LCDLR2_t;

typedef struct dw_ddr_ctl_PHY_DX0MDLR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 mdld:8;
	UINT32 tprd:8;
	UINT32 iprd:8;
#else
	UINT32 iprd:8;
	UINT32 tprd:8;
	UINT32 mdld:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX0MDLR_t;

typedef struct dw_ddr_ctl_PHY_DX1GCR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:20;
	UINT32 dqsrpd:1;
	UINT32 dxpdr:1;
	UINT32 dxpdd:1;
	UINT32 mdlen:1;
	UINT32 wlrken:4;
	UINT32 dxiom:1;
	UINT32 dxodt:1;
	UINT32 calbyp:1;
	UINT32 dxen:1;
#else
	UINT32 dxen:1;
	UINT32 calbyp:1;
	UINT32 dxodt:1;
	UINT32 dxiom:1;
	UINT32 wlrken:4;
	UINT32 mdlen:1;
	UINT32 dxpdd:1;
	UINT32 dxpdr:1;
	UINT32 dqsrpd:1;
	UINT32 rsv0:20;
#endif
} dw_ddr_ctl_PHY_DX1GCR_t;

typedef struct dw_ddr_ctl_PHY_DX1GSR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 gdqsprd:8;
	UINT32 dplock:1;
	UINT32 wlprd:8;
	UINT32 wlerr:1;
	UINT32 wldone:1;
	UINT32 wlcal:1;
	UINT32 gdqscal:1;
	UINT32 rdqsncal:1;
	UINT32 rdqscal:1;
	UINT32 wdqcal:1;
#else
	UINT32 wdqcal:1;
	UINT32 rdqscal:1;
	UINT32 rdqsncal:1;
	UINT32 gdqscal:1;
	UINT32 wlcal:1;
	UINT32 wldone:1;
	UINT32 wlerr:1;
	UINT32 wlprd:8;
	UINT32 dplock:1;
	UINT32 gdqsprd:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX1GSR0_t;

typedef struct dw_ddr_ctl_PHY_DX1GSR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:13;
	UINT32 dltcode:18;
	UINT32 dltdone:1;
#else
	UINT32 dltdone:1;
	UINT32 dltcode:18;
	UINT32 rsv0:13;
#endif
} dw_ddr_ctl_PHY_DX1GSR1_t;

typedef struct dw_ddr_ctl_PHY_DX1BDLR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dq4wbd:6;
	UINT32 dq3wbd:6;
	UINT32 dq2wbd:6;
	UINT32 dq1wbd:6;
	UINT32 dq0wbd:6;
#else
	UINT32 dq0wbd:6;
	UINT32 dq1wbd:6;
	UINT32 dq2wbd:6;
	UINT32 dq3wbd:6;
	UINT32 dq4wbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX1BDLR0_t;

typedef struct dw_ddr_ctl_PHY_DX1BDLR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dswbd:6;
	UINT32 dmwbd:6;
	UINT32 dq7wbd:6;
	UINT32 dq6wbd:6;
	UINT32 dq5wbd:6;
#else
	UINT32 dq5wbd:6;
	UINT32 dq6wbd:6;
	UINT32 dq7wbd:6;
	UINT32 dmwbd:6;
	UINT32 dswbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX1BDLR1_t;

typedef struct dw_ddr_ctl_PHY_DX1BDLR2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 dsnrbd:6;
	UINT32 dsrbd:6;
	UINT32 dqoebd:6;
	UINT32 dsoebd:6;
#else
	UINT32 dsoebd:6;
	UINT32 dqoebd:6;
	UINT32 dsrbd:6;
	UINT32 dsnrbd:6;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX1BDLR2_t;

typedef struct dw_ddr_ctl_PHY_DX1BDLR3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dq4rbd:6;
	UINT32 dq3rbd:6;
	UINT32 dq2rbd:6;
	UINT32 dq1rbd:6;
	UINT32 dq0rbd:6;
#else
	UINT32 dq0rbd:6;
	UINT32 dq1rbd:6;
	UINT32 dq2rbd:6;
	UINT32 dq3rbd:6;
	UINT32 dq4rbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX1BDLR3_t;

typedef struct dw_ddr_ctl_PHY_DX1BDLR4_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 dmrbd:6;
	UINT32 dq7rbd:6;
	UINT32 dq6rbd:6;
	UINT32 dq5rbd:6;
#else
	UINT32 dq5rbd:6;
	UINT32 dq6rbd:6;
	UINT32 dq7rbd:6;
	UINT32 dmrbd:6;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX1BDLR4_t;

typedef struct dw_ddr_ctl_PHY_DX1LCDLR0_s
{
#ifdef BIG_ENDIAN
	UINT32 r3wld:8;
	UINT32 r2wld:8;
	UINT32 r1wld:8;
	UINT32 r0wld:8;
#else
	UINT32 r0wld:8;
	UINT32 r1wld:8;
	UINT32 r2wld:8;
	UINT32 r3wld:8;
#endif
} dw_ddr_ctl_PHY_DX1LCDLR0_t;

typedef struct dw_ddr_ctl_PHY_DX1LCDLR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 rdqsnd:8;
	UINT32 rdqsd:8;
	UINT32 wdqd:8;
#else
	UINT32 wdqd:8;
	UINT32 rdqsd:8;
	UINT32 rdqsnd:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX1LCDLR1_t;

typedef struct dw_ddr_ctl_PHY_DX1LCDLR2_s
{
#ifdef BIG_ENDIAN
	UINT32 r3dqsgd:8;
	UINT32 r2dqsgd:8;
	UINT32 r1dqsgd:8;
	UINT32 r0dqsgd:8;
#else
	UINT32 r0dqsgd:8;
	UINT32 r1dqsgd:8;
	UINT32 r2dqsgd:8;
	UINT32 r3dqsgd:8;
#endif
} dw_ddr_ctl_PHY_DX1LCDLR2_t;

typedef struct dw_ddr_ctl_PHY_DX1MDLR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 mdld:8;
	UINT32 tprd:8;
	UINT32 iprd:8;
#else
	UINT32 iprd:8;
	UINT32 tprd:8;
	UINT32 mdld:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX1MDLR_t;

typedef struct dw_ddr_ctl_PHY_DX2GCR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:20;
	UINT32 dqsrpd:1;
	UINT32 dxpdr:1;
	UINT32 dxpdd:1;
	UINT32 mdlen:1;
	UINT32 wlrken:4;
	UINT32 dxiom:1;
	UINT32 dxodt:1;
	UINT32 calbyp:1;
	UINT32 dxen:1;
#else
	UINT32 dxen:1;
	UINT32 calbyp:1;
	UINT32 dxodt:1;
	UINT32 dxiom:1;
	UINT32 wlrken:4;
	UINT32 mdlen:1;
	UINT32 dxpdd:1;
	UINT32 dxpdr:1;
	UINT32 dqsrpd:1;
	UINT32 rsv0:20;
#endif
} dw_ddr_ctl_PHY_DX2GCR_t;

typedef struct dw_ddr_ctl_PHY_DX2GSR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 gdqsprd:8;
	UINT32 dplock:1;
	UINT32 wlprd:8;
	UINT32 wlerr:1;
	UINT32 wldone:1;
	UINT32 wlcal:1;
	UINT32 gdqscal:1;
	UINT32 rdqsncal:1;
	UINT32 rdqscal:1;
	UINT32 wdqcal:1;
#else
	UINT32 wdqcal:1;
	UINT32 rdqscal:1;
	UINT32 rdqsncal:1;
	UINT32 gdqscal:1;
	UINT32 wlcal:1;
	UINT32 wldone:1;
	UINT32 wlerr:1;
	UINT32 wlprd:8;
	UINT32 dplock:1;
	UINT32 gdqsprd:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX2GSR0_t;

typedef struct dw_ddr_ctl_PHY_DX2GSR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:13;
	UINT32 dltcode:18;
	UINT32 dltdone:1;
#else
	UINT32 dltdone:1;
	UINT32 dltcode:18;
	UINT32 rsv0:13;
#endif
} dw_ddr_ctl_PHY_DX2GSR1_t;

typedef struct dw_ddr_ctl_PHY_DX2BDLR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dq4wbd:6;
	UINT32 dq3wbd:6;
	UINT32 dq2wbd:6;
	UINT32 dq1wbd:6;
	UINT32 dq0wbd:6;
#else
	UINT32 dq0wbd:6;
	UINT32 dq1wbd:6;
	UINT32 dq2wbd:6;
	UINT32 dq3wbd:6;
	UINT32 dq4wbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX2BDLR0_t;

typedef struct dw_ddr_ctl_PHY_DX2BDLR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dswbd:6;
	UINT32 dmwbd:6;
	UINT32 dq7wbd:6;
	UINT32 dq6wbd:6;
	UINT32 dq5wbd:6;
#else
	UINT32 dq5wbd:6;
	UINT32 dq6wbd:6;
	UINT32 dq7wbd:6;
	UINT32 dmwbd:6;
	UINT32 dswbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX2BDLR1_t;

typedef struct dw_ddr_ctl_PHY_DX2BDLR2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 dsnrbd:6;
	UINT32 dsrbd:6;
	UINT32 dqoebd:6;
	UINT32 dsoebd:6;
#else
	UINT32 dsoebd:6;
	UINT32 dqoebd:6;
	UINT32 dsrbd:6;
	UINT32 dsnrbd:6;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX2BDLR2_t;

typedef struct dw_ddr_ctl_PHY_DX2BDLR3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dq4rbd:6;
	UINT32 dq3rbd:6;
	UINT32 dq2rbd:6;
	UINT32 dq1rbd:6;
	UINT32 dq0rbd:6;
#else
	UINT32 dq0rbd:6;
	UINT32 dq1rbd:6;
	UINT32 dq2rbd:6;
	UINT32 dq3rbd:6;
	UINT32 dq4rbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX2BDLR3_t;

typedef struct dw_ddr_ctl_PHY_DX2BDLR4_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 dmrbd:6;
	UINT32 dq7rbd:6;
	UINT32 dq6rbd:6;
	UINT32 dq5rbd:6;
#else
	UINT32 dq5rbd:6;
	UINT32 dq6rbd:6;
	UINT32 dq7rbd:6;
	UINT32 dmrbd:6;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX2BDLR4_t;

typedef struct dw_ddr_ctl_PHY_DX2LCDLR0_s
{
#ifdef BIG_ENDIAN
	UINT32 r3wld:8;
	UINT32 r2wld:8;
	UINT32 r1wld:8;
	UINT32 r0wld:8;
#else
	UINT32 r0wld:8;
	UINT32 r1wld:8;
	UINT32 r2wld:8;
	UINT32 r3wld:8;
#endif
} dw_ddr_ctl_PHY_DX2LCDLR0_t;

typedef struct dw_ddr_ctl_PHY_DX2LCDLR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 rdqsnd:8;
	UINT32 rdqsd:8;
	UINT32 wdqd:8;
#else
	UINT32 wdqd:8;
	UINT32 rdqsd:8;
	UINT32 rdqsnd:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX2LCDLR1_t;

typedef struct dw_ddr_ctl_PHY_DX2LCDLR2_s
{
#ifdef BIG_ENDIAN
	UINT32 r3dqsgd:8;
	UINT32 r2dqsgd:8;
	UINT32 r1dqsgd:8;
	UINT32 r0dqsgd:8;
#else
	UINT32 r0dqsgd:8;
	UINT32 r1dqsgd:8;
	UINT32 r2dqsgd:8;
	UINT32 r3dqsgd:8;
#endif
} dw_ddr_ctl_PHY_DX2LCDLR2_t;

typedef struct dw_ddr_ctl_PHY_DX2MDLR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 mdld:8;
	UINT32 tprd:8;
	UINT32 iprd:8;
#else
	UINT32 iprd:8;
	UINT32 tprd:8;
	UINT32 mdld:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX2MDLR_t;

typedef struct dw_ddr_ctl_PHY_DX3GCR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:20;
	UINT32 dqsrpd:1;
	UINT32 dxpdr:1;
	UINT32 dxpdd:1;
	UINT32 mdlen:1;
	UINT32 wlrken:4;
	UINT32 dxiom:1;
	UINT32 dxodt:1;
	UINT32 calbyp:1;
	UINT32 dxen:1;
#else
	UINT32 dxen:1;
	UINT32 calbyp:1;
	UINT32 dxodt:1;
	UINT32 dxiom:1;
	UINT32 wlrken:4;
	UINT32 mdlen:1;
	UINT32 dxpdd:1;
	UINT32 dxpdr:1;
	UINT32 dqsrpd:1;
	UINT32 rsv0:20;
#endif
} dw_ddr_ctl_PHY_DX3GCR_t;

typedef struct dw_ddr_ctl_PHY_DX3GSR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 gdqsprd:8;
	UINT32 dplock:1;
	UINT32 wlprd:8;
	UINT32 wlerr:1;
	UINT32 wldone:1;
	UINT32 wlcal:1;
	UINT32 gdqscal:1;
	UINT32 rdqsncal:1;
	UINT32 rdqscal:1;
	UINT32 wdqcal:1;
#else
	UINT32 wdqcal:1;
	UINT32 rdqscal:1;
	UINT32 rdqsncal:1;
	UINT32 gdqscal:1;
	UINT32 wlcal:1;
	UINT32 wldone:1;
	UINT32 wlerr:1;
	UINT32 wlprd:8;
	UINT32 dplock:1;
	UINT32 gdqsprd:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX3GSR0_t;

typedef struct dw_ddr_ctl_PHY_DX3GSR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:13;
	UINT32 dltcode:18;
	UINT32 dltdone:1;
#else
	UINT32 dltdone:1;
	UINT32 dltcode:18;
	UINT32 rsv0:13;
#endif
} dw_ddr_ctl_PHY_DX3GSR1_t;

typedef struct dw_ddr_ctl_PHY_DX3BDLR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dq4wbd:6;
	UINT32 dq3wbd:6;
	UINT32 dq2wbd:6;
	UINT32 dq1wbd:6;
	UINT32 dq0wbd:6;
#else
	UINT32 dq0wbd:6;
	UINT32 dq1wbd:6;
	UINT32 dq2wbd:6;
	UINT32 dq3wbd:6;
	UINT32 dq4wbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX3BDLR0_t;

typedef struct dw_ddr_ctl_PHY_DX3BDLR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dswbd:6;
	UINT32 dmwbd:6;
	UINT32 dq7wbd:6;
	UINT32 dq6wbd:6;
	UINT32 dq5wbd:6;
#else
	UINT32 dq5wbd:6;
	UINT32 dq6wbd:6;
	UINT32 dq7wbd:6;
	UINT32 dmwbd:6;
	UINT32 dswbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX3BDLR1_t;

typedef struct dw_ddr_ctl_PHY_DX3BDLR2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 dsnrbd:6;
	UINT32 dsrbd:6;
	UINT32 dqoebd:6;
	UINT32 dsoebd:6;
#else
	UINT32 dsoebd:6;
	UINT32 dqoebd:6;
	UINT32 dsrbd:6;
	UINT32 dsnrbd:6;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX3BDLR2_t;

typedef struct dw_ddr_ctl_PHY_DX3BDLR3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dq4rbd:6;
	UINT32 dq3rbd:6;
	UINT32 dq2rbd:6;
	UINT32 dq1rbd:6;
	UINT32 dq0rbd:6;
#else
	UINT32 dq0rbd:6;
	UINT32 dq1rbd:6;
	UINT32 dq2rbd:6;
	UINT32 dq3rbd:6;
	UINT32 dq4rbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX3BDLR3_t;

typedef struct dw_ddr_ctl_PHY_DX3BDLR4_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 dmrbd:6;
	UINT32 dq7rbd:6;
	UINT32 dq6rbd:6;
	UINT32 dq5rbd:6;
#else
	UINT32 dq5rbd:6;
	UINT32 dq6rbd:6;
	UINT32 dq7rbd:6;
	UINT32 dmrbd:6;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX3BDLR4_t;

typedef struct dw_ddr_ctl_PHY_DX3LCDLR0_s
{
#ifdef BIG_ENDIAN
	UINT32 r3wld:8;
	UINT32 r2wld:8;
	UINT32 r1wld:8;
	UINT32 r0wld:8;
#else
	UINT32 r0wld:8;
	UINT32 r1wld:8;
	UINT32 r2wld:8;
	UINT32 r3wld:8;
#endif
} dw_ddr_ctl_PHY_DX3LCDLR0_t;

typedef struct dw_ddr_ctl_PHY_DX3LCDLR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 rdqsnd:8;
	UINT32 rdqsd:8;
	UINT32 wdqd:8;
#else
	UINT32 wdqd:8;
	UINT32 rdqsd:8;
	UINT32 rdqsnd:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX3LCDLR1_t;

typedef struct dw_ddr_ctl_PHY_DX3LCDLR2_s
{
#ifdef BIG_ENDIAN
	UINT32 r3dqsgd:8;
	UINT32 r2dqsgd:8;
	UINT32 r1dqsgd:8;
	UINT32 r0dqsgd:8;
#else
	UINT32 r0dqsgd:8;
	UINT32 r1dqsgd:8;
	UINT32 r2dqsgd:8;
	UINT32 r3dqsgd:8;
#endif
} dw_ddr_ctl_PHY_DX3LCDLR2_t;

typedef struct dw_ddr_ctl_PHY_DX3MDLR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 mdld:8;
	UINT32 tprd:8;
	UINT32 iprd:8;
#else
	UINT32 iprd:8;
	UINT32 tprd:8;
	UINT32 mdld:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX3MDLR_t;

typedef struct dw_ddr_ctl_PHY_DX4GCR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:20;
	UINT32 dqsrpd:1;
	UINT32 dxpdr:1;
	UINT32 dxpdd:1;
	UINT32 mdlen:1;
	UINT32 wlrken:4;
	UINT32 dxiom:1;
	UINT32 dxodt:1;
	UINT32 calbyp:1;
	UINT32 dxen:1;
#else
	UINT32 dxen:1;
	UINT32 calbyp:1;
	UINT32 dxodt:1;
	UINT32 dxiom:1;
	UINT32 wlrken:4;
	UINT32 mdlen:1;
	UINT32 dxpdd:1;
	UINT32 dxpdr:1;
	UINT32 dqsrpd:1;
	UINT32 rsv0:20;
#endif
} dw_ddr_ctl_PHY_DX4GCR_t;

typedef struct dw_ddr_ctl_PHY_DX4GSR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 gdqsprd:8;
	UINT32 dplock:1;
	UINT32 wlprd:8;
	UINT32 wlerr:1;
	UINT32 wldone:1;
	UINT32 wlcal:1;
	UINT32 gdqscal:1;
	UINT32 rdqsncal:1;
	UINT32 rdqscal:1;
	UINT32 wdqcal:1;
#else
	UINT32 wdqcal:1;
	UINT32 rdqscal:1;
	UINT32 rdqsncal:1;
	UINT32 gdqscal:1;
	UINT32 wlcal:1;
	UINT32 wldone:1;
	UINT32 wlerr:1;
	UINT32 wlprd:8;
	UINT32 dplock:1;
	UINT32 gdqsprd:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX4GSR0_t;

typedef struct dw_ddr_ctl_PHY_DX4GSR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:13;
	UINT32 dltcode:18;
	UINT32 dltdone:1;
#else
	UINT32 dltdone:1;
	UINT32 dltcode:18;
	UINT32 rsv0:13;
#endif
} dw_ddr_ctl_PHY_DX4GSR1_t;

typedef struct dw_ddr_ctl_PHY_DX4BDLR0_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dq4wbd:6;
	UINT32 dq3wbd:6;
	UINT32 dq2wbd:6;
	UINT32 dq1wbd:6;
	UINT32 dq0wbd:6;
#else
	UINT32 dq0wbd:6;
	UINT32 dq1wbd:6;
	UINT32 dq2wbd:6;
	UINT32 dq3wbd:6;
	UINT32 dq4wbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX4BDLR0_t;

typedef struct dw_ddr_ctl_PHY_DX4BDLR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dswbd:6;
	UINT32 dmwbd:6;
	UINT32 dq7wbd:6;
	UINT32 dq6wbd:6;
	UINT32 dq5wbd:6;
#else
	UINT32 dq5wbd:6;
	UINT32 dq6wbd:6;
	UINT32 dq7wbd:6;
	UINT32 dmwbd:6;
	UINT32 dswbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX4BDLR1_t;

typedef struct dw_ddr_ctl_PHY_DX4BDLR2_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 dsnrbd:6;
	UINT32 dsrbd:6;
	UINT32 dqoebd:6;
	UINT32 dsoebd:6;
#else
	UINT32 dsoebd:6;
	UINT32 dqoebd:6;
	UINT32 dsrbd:6;
	UINT32 dsnrbd:6;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX4BDLR2_t;

typedef struct dw_ddr_ctl_PHY_DX4BDLR3_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:2;
	UINT32 dq4rbd:6;
	UINT32 dq3rbd:6;
	UINT32 dq2rbd:6;
	UINT32 dq1rbd:6;
	UINT32 dq0rbd:6;
#else
	UINT32 dq0rbd:6;
	UINT32 dq1rbd:6;
	UINT32 dq2rbd:6;
	UINT32 dq3rbd:6;
	UINT32 dq4rbd:6;
	UINT32 rsv0:2;
#endif
} dw_ddr_ctl_PHY_DX4BDLR3_t;

typedef struct dw_ddr_ctl_PHY_DX4BDLR4_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 dmrbd:6;
	UINT32 dq7rbd:6;
	UINT32 dq6rbd:6;
	UINT32 dq5rbd:6;
#else
	UINT32 dq5rbd:6;
	UINT32 dq6rbd:6;
	UINT32 dq7rbd:6;
	UINT32 dmrbd:6;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX4BDLR4_t;

typedef struct dw_ddr_ctl_PHY_DX4LCDLR0_s
{
#ifdef BIG_ENDIAN
	UINT32 r3wld:8;
	UINT32 r2wld:8;
	UINT32 r1wld:8;
	UINT32 r0wld:8;
#else
	UINT32 r0wld:8;
	UINT32 r1wld:8;
	UINT32 r2wld:8;
	UINT32 r3wld:8;
#endif
} dw_ddr_ctl_PHY_DX4LCDLR0_t;

typedef struct dw_ddr_ctl_PHY_DX4LCDLR1_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 rdqsnd:8;
	UINT32 rdqsd:8;
	UINT32 wdqd:8;
#else
	UINT32 wdqd:8;
	UINT32 rdqsd:8;
	UINT32 rdqsnd:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX4LCDLR1_t;

typedef struct dw_ddr_ctl_PHY_DX4LCDLR2_s
{
#ifdef BIG_ENDIAN
	UINT32 r3dqsgd:8;
	UINT32 r2dqsgd:8;
	UINT32 r1dqsgd:8;
	UINT32 r0dqsgd:8;
#else
	UINT32 r0dqsgd:8;
	UINT32 r1dqsgd:8;
	UINT32 r2dqsgd:8;
	UINT32 r3dqsgd:8;
#endif
} dw_ddr_ctl_PHY_DX4LCDLR2_t;

typedef struct dw_ddr_ctl_PHY_DX4MDLR_s
{
#ifdef BIG_ENDIAN
	UINT32 rsv0:8;
	UINT32 mdld:8;
	UINT32 tprd:8;
	UINT32 iprd:8;
#else
	UINT32 iprd:8;
	UINT32 tprd:8;
	UINT32 mdld:8;
	UINT32 rsv0:8;
#endif
} dw_ddr_ctl_PHY_DX4MDLR_t;

//module typedef
typedef struct dw_ddr_ctl_if_module_s
{
	dw_ddr_ctl_CCR_t CCR;
	dw_ddr_ctl_DCR_t DCR;
	dw_ddr_ctl_PCR_t PCR;
	dw_ddr_ctl_CSR_t CSR;
	dw_ddr_ctl_DRR_t DRR;
	dw_ddr_ctl_TPR0_t TPR0;
	dw_ddr_ctl_TPR1_t TPR1;
	dw_ddr_ctl_TPR2_t TPR2;
	dw_ddr_ctl_TPR3_t TPR3;
	UINT32 rsv_20_44 [8];
	dw_ddr_ctl_ODTCR_t ODTCR;
	dw_ddr_ctl_PPER0_t PPER0;
	dw_ddr_ctl_PPER1_t PPER1;
	dw_ddr_ctl_PPER2_t PPER2;
	dw_ddr_ctl_PPER3_t PPER3;
	dw_ddr_ctl_TPR4_t TPR4;
	dw_ddr_ctl_ALPMR_t ALPMR;
	UINT32 rsv_5c_1f0 [100];
	dw_ddr_ctl_MR_MR0_t MR_MR0;
	dw_ddr_ctl_EMR_MR1_t EMR_MR1;
	dw_ddr_ctl_EMR2_MR2_t EMR2_MR2;
	dw_ddr_ctl_EMR3_MR3_t EMR3_MR3;
	dw_ddr_ctl_HPCR0_t HPCR0;
	dw_ddr_ctl_HPCR1_t HPCR1;
	dw_ddr_ctl_HPCR2_t HPCR2;
	dw_ddr_ctl_HPCR3_t HPCR3;
	dw_ddr_ctl_HPCR4_t HPCR4;
	dw_ddr_ctl_HPCR5_t HPCR5;
	dw_ddr_ctl_HPCR6_t HPCR6;
	dw_ddr_ctl_HPCR7_t HPCR7;
	dw_ddr_ctl_HPCR8_t HPCR8;
	dw_ddr_ctl_HPCR9_t HPCR9;
	dw_ddr_ctl_HPCR10_t HPCR10;
	dw_ddr_ctl_HPCR11_t HPCR11;
	dw_ddr_ctl_HPCR12_t HPCR12;
	dw_ddr_ctl_HPCR13_t HPCR13;
	dw_ddr_ctl_HPCR14_t HPCR14;
	dw_ddr_ctl_HPCR15_t HPCR15;
	dw_ddr_ctl_HPCR16_t HPCR16;
	dw_ddr_ctl_HPCR17_t HPCR17;
	dw_ddr_ctl_HPCR18_t HPCR18;
	dw_ddr_ctl_HPCR19_t HPCR19;
	dw_ddr_ctl_HPCR20_t HPCR20;
	dw_ddr_ctl_HPCR21_t HPCR21;
	dw_ddr_ctl_HPCR22_t HPCR22;
	dw_ddr_ctl_HPCR23_t HPCR23;
	dw_ddr_ctl_HPCR24_t HPCR24;
	dw_ddr_ctl_HPCR25_t HPCR25;
	dw_ddr_ctl_HPCR26_t HPCR26;
	dw_ddr_ctl_HPCR27_t HPCR27;
	dw_ddr_ctl_HPCR28_t HPCR28;
	dw_ddr_ctl_HPCR29_t HPCR29;
	dw_ddr_ctl_HPCR30_t HPCR30;
	dw_ddr_ctl_HPCR31_t HPCR31;
	dw_ddr_ctl_PQCR0_t PQCR0;
	dw_ddr_ctl_PQCR1_t PQCR1;
	dw_ddr_ctl_PQCR2_t PQCR2;
	dw_ddr_ctl_PQCR3_t PQCR3;
	dw_ddr_ctl_PQCR4_t PQCR4;
	dw_ddr_ctl_PQCR5_t PQCR5;
	dw_ddr_ctl_PQCR6_t PQCR6;
	dw_ddr_ctl_PQCR7_t PQCR7;
	dw_ddr_ctl_MMGCR_t MMGCR;
	UINT32 rsv_2a0_400 [87];
	dw_ddr_ctl_PUB_RIDR_t PUB_RIDR;
	dw_ddr_ctl_PHY_PIR_t PHY_PIR;
	dw_ddr_ctl_PHY_PGCR0_t PHY_PGCR0;
	dw_ddr_ctl_PHY_PGCR1_t PHY_PGCR1;
	dw_ddr_ctl_PHY_PGSR0_t PHY_PGSR0;
	dw_ddr_ctl_PHY_PGSR1_t PHY_PGSR1;
	dw_ddr_ctl_PHY_PLLCR_t PHY_PLLCR;
	dw_ddr_ctl_PHY_PTR0_t PHY_PTR0;
	dw_ddr_ctl_PHY_PTR1_t PHY_PTR1;
	dw_ddr_ctl_PHY_PTR2_t PHY_PTR2;
	dw_ddr_ctl_PHY_ACMDLR_t PHY_ACMDLR;
	dw_ddr_ctl_PHY_ACBDLR_t PHY_ACBDLR;
	dw_ddr_ctl_PHY_ACIOCR_t PHY_ACIOCR;
	dw_ddr_ctl_PHY_DXCCR_t PHY_DXCCR;
	UINT32 rsv_434_480 [18];
	dw_ddr_ctl_PUB_MISC_t PUB_MISC;
	dw_ddr_ctl_PUB_SMCTL_t PUB_SMCTL;
	dw_ddr_ctl_PUB_SMSTAT_t PUB_SMSTAT;
	dw_ddr_ctl_PUB_MR1_t PUB_MR1;
	dw_ddr_ctl_PUB_TWLMRD_t PUB_TWLMRD;
	dw_ddr_ctl_PUB_TR_ADDR0_t PUB_TR_ADDR0;
	dw_ddr_ctl_PUB_TR_ADDR1_t PUB_TR_ADDR1;
	dw_ddr_ctl_PUB_TR_ADDR2_t PUB_TR_ADDR2;
	dw_ddr_ctl_PUB_TR_ADDR3_t PUB_TR_ADDR3;
	dw_ddr_ctl_PUB_TR_RD_LCDL_t PUB_TR_RD_LCDL;
	dw_ddr_ctl_PUB_PPMCFG_t PUB_PPMCFG;
	dw_ddr_ctl_PUB_SLCR_t PUB_SLCR;
	UINT32 rsv_4ac_4b4 [1];
	dw_ddr_ctl_PUB_TR_WR_LCDL_t PUB_TR_WR_LCDL;
	UINT32 rsv_4b4_4c0 [2];
	dw_ddr_ctl_PUB_BSTCTL_t PUB_BSTCTL;
	dw_ddr_ctl_PUB_BSTSTAT_t PUB_BSTSTAT;
	dw_ddr_ctl_PUB_BSTCNT_t PUB_BSTCNT;
	dw_ddr_ctl_PUB_BSTWRD_t PUB_BSTWRD;
	dw_ddr_ctl_PUB_BSTMSK_t PUB_BSTMSK;
	dw_ddr_ctl_PUB_BSTSEED_t PUB_BSTSEED;
	dw_ddr_ctl_PUB_BSTDWEC_t PUB_BSTDWEC;
	dw_ddr_ctl_PUB_BSTAWEC_t PUB_BSTAWEC;
	UINT32 rsv_4dc_4f8 [6];
	dw_ddr_ctl_PUB_IPVR_t PUB_IPVR;
	dw_ddr_ctl_PUB_IPTR_t PUB_IPTR;
	UINT32 rsv_4fc_508 [2];
	dw_ddr_ctl_PUB_DWLCFG_0_t PUB_DWLCFG_0;
	dw_ddr_ctl_PUB_DWLCFG_1_t PUB_DWLCFG_1;
	dw_ddr_ctl_PUB_DWLCFG_2_t PUB_DWLCFG_2;
	dw_ddr_ctl_PUB_DWLCFG_3_t PUB_DWLCFG_3;
	dw_ddr_ctl_PUB_DRLCFG_0_t PUB_DRLCFG_0;
	dw_ddr_ctl_PUB_DRLCFG_1_t PUB_DRLCFG_1;
	dw_ddr_ctl_PUB_DRLCFG_2_t PUB_DRLCFG_2;
	dw_ddr_ctl_PUB_DRLCFG_3_t PUB_DRLCFG_3;
	UINT32 rsv_524_540 [6];
	dw_ddr_ctl_PHY_ZQ0CR0_t PHY_ZQ0CR0;
	dw_ddr_ctl_PHY_ZQ0CR1_t PHY_ZQ0CR1;
	UINT32 rsv_544_54c [1];
	dw_ddr_ctl_PHY_ZQ0SR0_t PHY_ZQ0SR0;
	dw_ddr_ctl_PHY_ZQ0SR1_t PHY_ZQ0SR1;
	UINT32 rsv_550_5c0 [27];
	dw_ddr_ctl_PHY_DX0GCR_t PHY_DX0GCR;
	dw_ddr_ctl_PHY_DX0GSR0_t PHY_DX0GSR0;
	dw_ddr_ctl_PHY_DX0GSR1_t PHY_DX0GSR1;
	dw_ddr_ctl_PHY_DX0BDLR0_t PHY_DX0BDLR0;
	dw_ddr_ctl_PHY_DX0BDLR1_t PHY_DX0BDLR1;
	dw_ddr_ctl_PHY_DX0BDLR2_t PHY_DX0BDLR2;
	dw_ddr_ctl_PHY_DX0BDLR3_t PHY_DX0BDLR3;
	dw_ddr_ctl_PHY_DX0BDLR4_t PHY_DX0BDLR4;
	dw_ddr_ctl_PHY_DX0LCDLR0_t PHY_DX0LCDLR0;
	dw_ddr_ctl_PHY_DX0LCDLR1_t PHY_DX0LCDLR1;
	dw_ddr_ctl_PHY_DX0LCDLR2_t PHY_DX0LCDLR2;
	dw_ddr_ctl_PHY_DX0MDLR_t PHY_DX0MDLR;
	UINT32 rsv_5ec_600 [4];
	dw_ddr_ctl_PHY_DX1GCR_t PHY_DX1GCR;
	dw_ddr_ctl_PHY_DX1GSR0_t PHY_DX1GSR0;
	dw_ddr_ctl_PHY_DX1GSR1_t PHY_DX1GSR1;
	dw_ddr_ctl_PHY_DX1BDLR0_t PHY_DX1BDLR0;
	dw_ddr_ctl_PHY_DX1BDLR1_t PHY_DX1BDLR1;
	dw_ddr_ctl_PHY_DX1BDLR2_t PHY_DX1BDLR2;
	dw_ddr_ctl_PHY_DX1BDLR3_t PHY_DX1BDLR3;
	dw_ddr_ctl_PHY_DX1BDLR4_t PHY_DX1BDLR4;
	dw_ddr_ctl_PHY_DX1LCDLR0_t PHY_DX1LCDLR0;
	dw_ddr_ctl_PHY_DX1LCDLR1_t PHY_DX1LCDLR1;
	dw_ddr_ctl_PHY_DX1LCDLR2_t PHY_DX1LCDLR2;
	dw_ddr_ctl_PHY_DX1MDLR_t PHY_DX1MDLR;
	UINT32 rsv_62c_640 [4];
	dw_ddr_ctl_PHY_DX2GCR_t PHY_DX2GCR;
	dw_ddr_ctl_PHY_DX2GSR0_t PHY_DX2GSR0;
	dw_ddr_ctl_PHY_DX2GSR1_t PHY_DX2GSR1;
	dw_ddr_ctl_PHY_DX2BDLR0_t PHY_DX2BDLR0;
	dw_ddr_ctl_PHY_DX2BDLR1_t PHY_DX2BDLR1;
	dw_ddr_ctl_PHY_DX2BDLR2_t PHY_DX2BDLR2;
	dw_ddr_ctl_PHY_DX2BDLR3_t PHY_DX2BDLR3;
	dw_ddr_ctl_PHY_DX2BDLR4_t PHY_DX2BDLR4;
	dw_ddr_ctl_PHY_DX2LCDLR0_t PHY_DX2LCDLR0;
	dw_ddr_ctl_PHY_DX2LCDLR1_t PHY_DX2LCDLR1;
	dw_ddr_ctl_PHY_DX2LCDLR2_t PHY_DX2LCDLR2;
	dw_ddr_ctl_PHY_DX2MDLR_t PHY_DX2MDLR;
	UINT32 rsv_66c_680 [4];
	dw_ddr_ctl_PHY_DX3GCR_t PHY_DX3GCR;
	dw_ddr_ctl_PHY_DX3GSR0_t PHY_DX3GSR0;
	dw_ddr_ctl_PHY_DX3GSR1_t PHY_DX3GSR1;
	dw_ddr_ctl_PHY_DX3BDLR0_t PHY_DX3BDLR0;
	dw_ddr_ctl_PHY_DX3BDLR1_t PHY_DX3BDLR1;
	dw_ddr_ctl_PHY_DX3BDLR2_t PHY_DX3BDLR2;
	dw_ddr_ctl_PHY_DX3BDLR3_t PHY_DX3BDLR3;
	dw_ddr_ctl_PHY_DX3BDLR4_t PHY_DX3BDLR4;
	dw_ddr_ctl_PHY_DX3LCDLR0_t PHY_DX3LCDLR0;
	dw_ddr_ctl_PHY_DX3LCDLR1_t PHY_DX3LCDLR1;
	dw_ddr_ctl_PHY_DX3LCDLR2_t PHY_DX3LCDLR2;
	dw_ddr_ctl_PHY_DX3MDLR_t PHY_DX3MDLR;
	UINT32 rsv_6ac_6c0 [4];
	dw_ddr_ctl_PHY_DX4GCR_t PHY_DX4GCR;
	dw_ddr_ctl_PHY_DX4GSR0_t PHY_DX4GSR0;
	dw_ddr_ctl_PHY_DX4GSR1_t PHY_DX4GSR1;
	dw_ddr_ctl_PHY_DX4BDLR0_t PHY_DX4BDLR0;
	dw_ddr_ctl_PHY_DX4BDLR1_t PHY_DX4BDLR1;
	dw_ddr_ctl_PHY_DX4BDLR2_t PHY_DX4BDLR2;
	dw_ddr_ctl_PHY_DX4BDLR3_t PHY_DX4BDLR3;
	dw_ddr_ctl_PHY_DX4BDLR4_t PHY_DX4BDLR4;
	dw_ddr_ctl_PHY_DX4LCDLR0_t PHY_DX4LCDLR0;
	dw_ddr_ctl_PHY_DX4LCDLR1_t PHY_DX4LCDLR1;
	dw_ddr_ctl_PHY_DX4LCDLR2_t PHY_DX4LCDLR2;
	dw_ddr_ctl_PHY_DX4MDLR_t PHY_DX4MDLR;
} dw_ddr_ctl_if_module_t;

extern dw_ddr_ctl_if_module_t *dw_ddr_ctl_if_module;

#ifdef __cplusplus
}
#endif
#endif /* _dw_ddr_ctl_if_HW_REGS_H*/

