export PS1=uMonuIP:
export EDITOR=vi
export TITLE="MicroMonitor uIP Application"
export UMONTOP=../../umon_main
export HOME=`pwd`
unset TERM
. $UMONTOP/host/bin/umon_setup
export TARGET_IP=192.168.1.110
