tfs run test_list.script
set SW_SAFE_REG 0xe573E008
set SW_TEMP_MEM 0xd0400000
# TOP:
dm -4 -v last_test $SW_SAFE_REG
set -a last_test 0x7fff
pm -4 $SW_TEMP_MEM $last_test
dm -4 -d -v last_test $SW_TEMP_MEM
if $last_test eq 0 goto FIRST_TEST
set test $last_test
goto NEXT_TEST:

# FIRST_TEST:
echo Start_All_Tests
# NEXT_TEST:
if $test gt $max_test goto DONE
echo Starting ${TEST_${test}}
tfs run test.script ${TEST_${test}}
echo Finished ${TEST_${test}}
set -i test
pm -4 $SW_SAFE_REG $test
reset
goto TOP
# DONE:
pm -4 $SW_SAFE_REG 0
echo End_All_Tests
